import { invoke } from "@tauri-apps/api/core";
import { emitTo, listen, type UnlistenFn } from "@tauri-apps/api/event";
import type { Language } from "../shared/i18n";
import type { Look } from "../shared/look";
import type {
  Account,
  Acting,
  Adopted,
  Artifact,
  AttachedFile,
  Attachments,
  Avoided,
  BarContext,
  BarOpened,
  BarProject,
  Capabilities,
  Card,
  Changes,
  ChatEvent,
  ClaudeCodeProgress,
  Decision,
  Detail,
  Entry,
  Excepted,
  Finding,
  Found,
  Frame,
  HandOver,
  Heard,
  Imported,
  Isolation,
  Listing,
  Market,
  Message,
  Method,
  Microphone,
  News,
  NewServer,
  Opened,
  Profile,
  ProjectRules,
  Provider,
  ProviderState,
  Repo,
  Restored,
  SessionEntry,
  Settings,
  Shortcut,
  ShortcutKeys,
  Shot,
  Slash,
  TerminalHeard,
  TerminalOpened,
  TerminalAdopted,
  UpdateCheck,
  UpdateStage,
  VoiceHeard,
  VoiceModel,
  Watching,
  Workspace,
} from "./types";

export type CapabilityKind = "skill" | "server" | "plugin";

const HOST = "main";

export const commands = {
  profile: () => invoke<Profile>("profile"),
  saveProfile: (name: string) => invoke<void>("save_profile", { name }),
  setUpdateCheck: (on: boolean) => invoke<void>("set_update_check", { on }),
  setNotify: (on: boolean) => invoke<void>("set_notify", { on }),
  setKeepInTray: (on: boolean) => invoke<void>("set_keep_in_tray", { on }),
  setStartWithWindows: (on: boolean) => invoke<void>("set_start_with_windows", { on }),
  shortcutState: () => invoke<Shortcut>("shortcut_state"),
  shortcutSet: (keys: ShortcutKeys) => invoke<Shortcut>("shortcut_set", { keys }),
  shortcutPause: (paused: boolean) => invoke<void>("shortcut_pause", { paused }),
  notify: (title: string, body: string) => invoke<void>("notify", { title, body }),
  setWelcomed: (on: boolean) => invoke<void>("set_welcomed", { on }),
  news: () => invoke<News[]>("news"),
  sawNews: () => invoke<void>("saw_news"),
  setLook: (look: Look) => invoke<void>("set_look", { look }),
  setLanguage: (language: Language) => invoke<void>("set_language", { language }),
  welcomeScan: () => invoke<Found>("welcome_scan"),
  welcomeAdopt: (roots: string[]) => invoke<Adopted>("welcome_adopt", { roots }),
  welcomeServers: (ids: string[], roots: string[]) => invoke<Imported>("welcome_servers", { ids, roots }),
  updateCheck: (manual: boolean) => invoke<UpdateCheck>("update_check", { manual }),
  updateInstall: () => invoke<void>("update_install"),
  chatWorking: () => invoke<number>("chat_working"),
  providersState: () => invoke<ProviderState[]>("providers_state"),
  providers: () => invoke<Provider[]>("providers"),
  models: (provider: string) => invoke<Card[] | null>("models", { provider }),
  claudeAccount: () => invoke<Account | null>("claude_account"),
  setProviderMethod: (id: string, method: Method) => invoke<void>("set_provider_method", { id, method }),
  saveApiKey: (id: string, key: string) => invoke<void>("save_api_key", { id, key }),
  forgetApiKey: (id: string) => invoke<void>("forget_api_key", { id }),
  providerSignIn: (method: Method) => invoke<void>("provider_sign_in", { method }),
  providerSignOut: () => invoke<void>("provider_sign_out"),
  claudeCodeInstall: () => invoke<string>("claude_code_install"),
  claudeCodeNewer: () => invoke<string | null>("claude_code_newer"),
  claudeCodeUpdate: () => invoke<string>("claude_code_update"),

  capabilities: (root: string) => invoke<Capabilities>("capabilities", { root }),
  setCapability: (kind: CapabilityKind, root: string, name: string, enabled: boolean) =>
    invoke<void>(`set_${kind}`, { root, name, enabled }),
  removeCapability: (kind: CapabilityKind, name: string) => invoke<void>(`remove_${kind}`, { name }),
  skillText: (name: string) => invoke<string>("skill_text", { name }),
  createSkill: (root: string, name: string, description: string, body: string) =>
    invoke<void>("create_skill", { root, name, description, body }),
  importSkill: (root: string, path: string) => invoke<string>("import_skill", { root, path }),
  addServer: (root: string, server: NewServer) => invoke<void>("add_server", { root, server }),

  market: (refresh: boolean) => invoke<Market>("market", { refresh }),
  marketSearch: (query: string) => invoke<Listing[]>("market_search", { query }),
  marketDetail: (id: string) => invoke<Detail>("market_detail", { id }),
  marketFile: (id: string, path: string) => invoke<string>("market_file", { id, path }),
  marketInstall: (root: string, id: string, values: Record<string, string>) =>
    invoke<string>("market_install", { root, id, values }),
  marketUpdate: (id: string, name: string) => invoke<void>("market_update", { id, name }),

  replay: (root: string, id: string) => invoke<SessionEntry[]>("replay", { root, id }),
  newSessionId: () => invoke<string>("new_session_id"),
  openSession: (root: string, id: string | null) => invoke<string>("open_session", { root, id }),
  chatWarm: (root: string, sessionId: string, settings: Settings) => invoke<Slash[]>("chat_warm", { root, sessionId, settings }),
  chatSend: (root: string, sessionId: string, message: Message, settings: Settings) =>
    invoke<void>("chat_send", { root, sessionId, message, settings }),
  chatStop: (sessionId: string) => invoke<void>("chat_stop", { sessionId }),
  chatAnswer: (sessionId: string, request: string, decision: Decision) => invoke<void>("chat_answer", { sessionId, request, decision }),
  chatBusy: (sessionId: string) => invoke<boolean>("chat_busy", { sessionId }),
  canonHeld: (work: string) => invoke<Finding[] | null>("canon_held", { work }),
  canonAccept: (work: string) => invoke<void>("canon_accept", { work }),
  canonUndo: (work: string) => invoke<Restored>("canon_undo", { work }),
  canonFix: (work: string) => invoke<string | null>("canon_fix", { work }),
  canonRetry: (sessionId: string) => invoke<void>("canon_retry", { sessionId }),
  canonExceptions: (work: string) => invoke<Excepted[]>("canon_exceptions", { work }),
  canonRetract: (work: string, key: string) => invoke<void>("canon_retract", { work, key }),
  canonRules: (work: string) => invoke<ProjectRules>("canon_rules", { work }),
  canonSetRules: (work: string, rules: ProjectRules) => invoke<void>("canon_set_rules", { work, rules }),
  canonAvoided: (work: string, since: number) => invoke<Avoided>("canon_avoided", { work, since }),
  chatTasks: (sessionId: string) => invoke<string[]>("chat_tasks", { sessionId }),

  workspaces: () => invoke<Workspace[]>("workspaces"),
  titleSession: (root: string, id: string) => invoke<string | null>("title_session", { root, id }),
  renameSession: (root: string, id: string, title: string) => invoke<string>("rename_session", { root, id, title }),
  archiveSession: (root: string, id: string, archived: boolean) => invoke<void>("archive_session", { root, id, archived }),
  deleteSession: (root: string, id: string) => invoke<void>("delete_session", { root, id }),
  isolateSession: (root: string, id: string) => invoke<Isolation>("isolate_session", { root, id }),

  artifacts: () => invoke<Artifact[]>("artifacts"),
  artifactData: (path: string) => invoke<string>("artifact_data", { path }),
  artifactText: (path: string) => invoke<string>("artifact_text", { path }),
  openExternal: (target: string) => invoke<void>("open_external", { target }),

  previewUrl: (root: string, path: string) => invoke<string>("preview_url", { root, path }),
  browserOpen: (url: string, frame: Frame, zoom: number) => invoke<void>("browser_open", { url, frame, zoom }),
  browserPlace: (frame: Frame, zoom: number) => invoke<void>("browser_place", { frame, zoom }),
  browserShow: (shown: boolean) => invoke<void>("browser_show", { shown }),
  browserAct: (act: "back" | "forward" | "reload" | "close") => invoke<void>("browser_act", { act }),

  terminalOpen: (root: string, cols: number, rows: number) => invoke<TerminalOpened>("terminal_open", { root, cols, rows }),
  terminalWrite: (id: number, data: string) => invoke<void>("terminal_write", { id, data }),
  terminalResize: (id: number, cols: number, rows: number) => invoke<void>("terminal_resize", { id, cols, rows }),
  terminalClose: (id: number) => invoke<void>("terminal_close", { id }),
  actAnswer: (ask: number, ok: boolean, text: string) => invoke<void>("act_answer", { ask, ok, text }),
  voiceStart: (language: string, handsFree = false) => invoke<number>("voice_start", { language, handsFree }),
  voiceTest: () => invoke<number>("voice_test"),
  voiceStop: () => invoke<void>("voice_stop"),
  voiceModel: () => invoke<VoiceModel>("voice_model"),
  voicePrepare: () => invoke<void>("voice_prepare"),
  voiceMicrophones: () => invoke<Microphone[]>("voice_microphones"),
  voiceMicrophone: () => invoke<string | null>("voice_microphone"),
  voiceChoose: (microphone: string | null) => invoke<void>("voice_choose", { microphone }),
  setWake: (on: boolean) => invoke<string | null>("set_wake", { on }),

  folder: (root: string, path: string) => invoke<Entry[]>("folder", { root, path }),
  findFiles: (root: string, needle: string) => invoke<Entry[]>("find_files", { root, needle }),
  changes: (root: string) => invoke<Changes | null>("changes", { root }),
  openFile: (root: string, path: string) => invoke<Opened>("open_file", { root, path }),
  attach: (root: string, paths: string[]) => invoke<Attachments>("attach", { root, paths }),
  stageFile: (name: string, data: string) => invoke<AttachedFile>("stage_file", { name, data }),
  repo: (root: string) => invoke<Repo | null>("repo", { root }),
  checkout: (root: string, branch: string) => invoke<Repo>("checkout", { root, branch }),
  remember: (root: string) => invoke<void>("remember", { root }),
  trustProject: (root: string, trusted: boolean) => invoke<void>("trust_project", { root, trusted }),
  projectTrusted: (root: string) => invoke<boolean>("project_trusted", { root }),
  lastProject: () => invoke<string | null>("last_project"),
  taskOutput: (path: string) => invoke<string>("task_output", { path }),
  stopTask: (sessionId: string, taskId: string) => invoke<void>("chat_stop_task", { sessionId, taskId }),

  barOpen: () => invoke<void>("bar_open"),
  barFocus: (hand: HandOver) => invoke<void>("bar_focus", { hand }),
  barHide: () => invoke<void>("bar_hide"),
  barFit: (height: number) => invoke<void>("bar_fit", { height }),
  barPin: (on: boolean) => invoke<void>("bar_pin", { on }),
  barDrag: () => invoke<void>("bar_drag"),
  barRecenter: () => invoke<void>("bar_recenter"),
  barHandOver: (hand: HandOver) => invoke<void>("bar_hand_over", { hand }),
  barContext: () => invoke<BarContext>("bar_context"),
  barClip: () => invoke<string | null>("bar_clip"),
  barShot: () => invoke<Shot | null>("bar_shot"),
  barProjects: () => invoke<BarProject[]>("bar_projects"),
  barWatching: (session: string | null) => emitTo<Watching>(HOST, "bar-watching", { session }),
};

export const events = {
  claudeCode: (heard: (progress: ClaudeCodeProgress) => void): Promise<UnlistenFn> =>
    listen<ClaudeCodeProgress>("claude-code", ({ payload }) => heard(payload)),
  browser: (heard: (what: Heard) => void): Promise<UnlistenFn> => listen<Heard>("browser", ({ payload }) => heard(payload)),
  terminal: (heard: (what: TerminalHeard) => void): Promise<UnlistenFn> =>
    listen<TerminalHeard>("terminal", ({ payload }) => heard(payload)),
  terminalAdopted: (heard: (adopted: TerminalAdopted) => void): Promise<UnlistenFn> =>
    listen<TerminalAdopted>("terminal-adopted", ({ payload }) => heard(payload)),
  act: (heard: (acting: Acting) => void): Promise<UnlistenFn> => listen<Acting>("sens-act", ({ payload }) => heard(payload)),
  voice: (heard: (what: VoiceHeard) => void): Promise<UnlistenFn> => listen<VoiceHeard>("voice", ({ payload }) => heard(payload)),
  welcome: (heard: (done: number, total: number) => void): Promise<UnlistenFn> =>
    listen<{ done: number; total: number }>("welcome", ({ payload }) => heard(payload.done, payload.total)),
  update: (heard: (stage: UpdateStage) => void): Promise<UnlistenFn> =>
    listen<{ version: string; stage: UpdateStage }>("update", ({ payload }) => heard(payload.stage)),
  chat: (heard: (session: string, event: ChatEvent) => void): Promise<UnlistenFn> =>
    listen<{ session: string; event: ChatEvent }>("chat", ({ payload }) => heard(payload.session, payload.event)),
  barOpen: (heard: (opened: BarOpened) => void): Promise<UnlistenFn> => listen<BarOpened>("bar-open", ({ payload }) => heard(payload)),
  barHandOver: (heard: (hand: HandOver) => void): Promise<UnlistenFn> => listen<HandOver>("bar-hand-over", ({ payload }) => heard(payload)),
  barWatching: (heard: (session: string | null) => void): Promise<UnlistenFn> =>
    listen<Watching>("bar-watching", ({ payload }) => heard(payload.session)),
};
