import { copy } from "../shared/i18n";

export const t = copy({
  en: {
    sidebarWidth: "Sidebar width",
    dockSize: { start: "Left panel width", end: "Right panel width", bottom: "Bottom panel height" },
    dock: { start: "Left", end: "Right", bottom: "Bottom" },
    moveHint: "Drag to another edge, or Alt and an arrow key",
    arrange: "Arrangement",
    arrangeKeys: (keys: string) => `Arrangement (${keys})`,
    arrangeSaid: "Drag a tab to an edge of the window, or start from one of these.",
    sessions: "Sessions",
    chat: "Chat",
    railSide: "Sidebar",
    wide: "Bottom panel across the full width",
    closedTools: "Closed",
    emptyDock: "Drop a tool",
    dropMove: "Drop to move it here",
    starts: "Start from",
    start: { conversation: "Conversation", code: "Code", review: "Review", preview: "Preview", explore: "Explore" },
    startSaid: {
      conversation: "Only the chat. The panels wait where they were",
      code: "Files and changes on the right, terminal below",
      review: "Changes beside the file they touch",
      preview: "The page on the right, terminal across the bottom",
      explore: "The map beside the code",
    },
    kept: "Kept",
    keepNow: "Keep this arrangement",
    keepName: "Name",
    keptName: (n: number) => `Arrangement ${n}`,
    forget: (name: string) => `Forget ${name}`,
    changed: "Arrangement changed",
    undo: "Undo",
    keep: "Keep",
    treeWidth: "File tree width",
    artifacts: "Artifacts",
    capabilities: "Capabilities",
    news: "What’s new",
    tool: { files: "Files", changes: "Changes", map: "Map", web: "Web", terminal: "Terminal", tasks: "Background" },
    toolSaid: {
      files: "The project’s tree and code",
      changes: "What differs from the last commit",
      map: "How the project is laid out and what depends on what",
      web: "Pages and local servers",
      terminal: "A shell in the project folder",
      tasks: "Subagents and the model’s commands",
    },
    tools: "Tools",
    closeTab: (name: string) => `Close ${name}`,
    split: "Show two at once",
    widen: "Show only this",
    dropPair: "Drop to show both",
    pairSize: "Split size",
    openTool: "Open a tool",
    refresh: "Refresh",
    fileTree: "File tree",
    showSidebar: "Show sidebar",
    hideSidebar: "Hide sidebar",
    updateAvailable: (version: string) => `Update available: Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} available`,
    update: "Update",
    minimize: "Minimize",
    focusMode: "Focus mode",
    focusModeKeys: (keys: string) => `Focus mode · Hide Sens and ask it from any window (${keys})`,
    maximize: "Maximize",
    restore: "Restore",
    chooseFolder: "Choose a working folder",
  },
  es: {
    sidebarWidth: "Ancho de la barra lateral",
    dockSize: { start: "Ancho del panel izquierdo", end: "Ancho del panel derecho", bottom: "Alto del panel inferior" },
    dock: { start: "Izquierda", end: "Derecha", bottom: "Abajo" },
    moveHint: "Arrástrala a otro borde, o Alt y una flecha",
    arrange: "Disposición",
    arrangeKeys: (keys: string) => `Disposición (${keys})`,
    arrangeSaid: "Arrastra una pestaña a un borde de la ventana, o parte de una de estas.",
    sessions: "Sesiones",
    chat: "Chat",
    railSide: "Barra lateral",
    wide: "Panel inferior a todo el ancho",
    closedTools: "Cerradas",
    emptyDock: "Suelta una herramienta",
    dropMove: "Suelta para moverla aquí",
    starts: "Partir de",
    start: { conversation: "Conversación", code: "Código", review: "Revisión", preview: "Vista previa", explore: "Exploración" },
    startSaid: {
      conversation: "Solo el chat. Los paneles esperan donde estaban",
      code: "Ficheros y cambios a la derecha, terminal abajo",
      review: "Los cambios junto al fichero que tocan",
      preview: "La página a la derecha, terminal a todo el ancho",
      explore: "El mapa junto al código",
    },
    kept: "Guardadas",
    keepNow: "Guardar esta disposición",
    keepName: "Nombre",
    keptName: (n: number) => `Disposición ${n}`,
    forget: (name: string) => `Olvidar ${name}`,
    changed: "Disposición cambiada",
    undo: "Deshacer",
    keep: "Guardar",
    treeWidth: "Ancho del árbol de ficheros",
    artifacts: "Artefactos",
    capabilities: "Capacidades",
    news: "Novedades",
    tool: { files: "Ficheros", changes: "Cambios", map: "Mapa", web: "Web", terminal: "Terminal", tasks: "Segundo plano" },
    toolSaid: {
      files: "El árbol y el código del proyecto",
      changes: "Lo que difiere del último commit",
      map: "Cómo se reparte el proyecto y qué depende de qué",
      web: "Páginas y servidores locales",
      terminal: "Una consola en la carpeta del proyecto",
      tasks: "Subagentes y comandos del modelo",
    },
    tools: "Herramientas",
    closeTab: (name: string) => `Cerrar ${name}`,
    split: "Ver dos a la vez",
    widen: "Ver solo esta",
    dropPair: "Suelta para ver las dos",
    pairSize: "Tamaño de la división",
    openTool: "Abrir una herramienta",
    refresh: "Actualizar",
    fileTree: "Árbol de ficheros",
    showSidebar: "Mostrar la barra lateral",
    hideSidebar: "Ocultar la barra lateral",
    updateAvailable: (version: string) => `Actualización disponible: Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} disponible`,
    update: "Actualizar",
    minimize: "Minimizar",
    focusMode: "Modo focus",
    focusModeKeys: (keys: string) => `Modo focus · Oculta Sens y pregúntale desde cualquier ventana (${keys})`,
    maximize: "Maximizar",
    restore: "Restaurar",
    chooseFolder: "Elige la carpeta de trabajo",
  },
  fr: {
    sidebarWidth: "Largeur de la barre latérale",
    dockSize: { start: "Largeur du panneau gauche", end: "Largeur du panneau droit", bottom: "Hauteur du panneau inférieur" },
    dock: { start: "Gauche", end: "Droite", bottom: "Bas" },
    moveHint: "Faites-le glisser vers un autre bord, ou Alt et une flèche",
    arrange: "Disposition",
    arrangeKeys: (keys: string) => `Disposition (${keys})`,
    arrangeSaid: "Faites glisser un onglet vers un bord de la fenêtre, ou partez de l’une de celles-ci.",
    sessions: "Sessions",
    chat: "Chat",
    railSide: "Barre latérale",
    wide: "Panneau inférieur sur toute la largeur",
    closedTools: "Fermés",
    emptyDock: "Déposez un outil",
    dropMove: "Déposez pour le placer ici",
    starts: "Partir de",
    start: { conversation: "Conversation", code: "Code", review: "Revue", preview: "Aperçu", explore: "Exploration" },
    startSaid: {
      conversation: "Seulement le chat. Les panneaux restent où ils étaient",
      code: "Fichiers et modifications à droite, terminal en bas",
      review: "Les modifications à côté du fichier qu’elles touchent",
      preview: "La page à droite, le terminal sur toute la largeur",
      explore: "La carte à côté du code",
    },
    kept: "Enregistrées",
    keepNow: "Enregistrer cette disposition",
    keepName: "Nom",
    keptName: (n: number) => `Disposition ${n}`,
    forget: (name: string) => `Oublier ${name}`,
    changed: "Disposition modifiée",
    undo: "Annuler",
    keep: "Enregistrer",
    treeWidth: "Largeur de l’arborescence",
    artifacts: "Artefacts",
    capabilities: "Capacités",
    news: "Nouveautés",
    tool: { files: "Fichiers", changes: "Modifications", map: "Carte", web: "Web", terminal: "Terminal", tasks: "Arrière-plan" },
    toolSaid: {
      files: "L’arborescence et le code du projet",
      changes: "Ce qui diffère du dernier commit",
      map: "Comment le projet est organisé et ce qui dépend de quoi",
      web: "Pages et serveurs locaux",
      terminal: "Une console dans le dossier du projet",
      tasks: "Sous-agents et commandes du modèle",
    },
    tools: "Outils",
    closeTab: (name: string) => `Fermer ${name}`,
    split: "Afficher deux à la fois",
    widen: "Afficher seulement celui-ci",
    dropPair: "Déposez pour voir les deux",
    pairSize: "Taille de la division",
    openTool: "Ouvrir un outil",
    refresh: "Actualiser",
    fileTree: "Arborescence des fichiers",
    showSidebar: "Afficher la barre latérale",
    hideSidebar: "Masquer la barre latérale",
    updateAvailable: (version: string) => `Mise à jour disponible : Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} disponible`,
    update: "Mettre à jour",
    minimize: "Réduire",
    focusMode: "Mode focus",
    focusModeKeys: (keys: string) => `Mode focus · Masquer Sens et lui demander depuis n’importe quelle fenêtre (${keys})`,
    maximize: "Agrandir",
    restore: "Restaurer",
    chooseFolder: "Choisissez le dossier de travail",
  },
  de: {
    sidebarWidth: "Breite der Seitenleiste",
    dockSize: { start: "Breite des linken Bereichs", end: "Breite des rechten Bereichs", bottom: "Höhe des unteren Bereichs" },
    dock: { start: "Links", end: "Rechts", bottom: "Unten" },
    moveHint: "An einen anderen Rand ziehen, oder Alt und eine Pfeiltaste",
    arrange: "Anordnung",
    arrangeKeys: (keys: string) => `Anordnung (${keys})`,
    arrangeSaid: "Ziehe einen Tab an einen Fensterrand oder beginne mit einer dieser Anordnungen.",
    sessions: "Sitzungen",
    chat: "Chat",
    railSide: "Seitenleiste",
    wide: "Unterer Bereich über die ganze Breite",
    closedTools: "Geschlossen",
    emptyDock: "Werkzeug ablegen",
    dropMove: "Ablegen, um es hierher zu verschieben",
    starts: "Beginnen mit",
    start: { conversation: "Gespräch", code: "Code", review: "Review", preview: "Vorschau", explore: "Erkunden" },
    startSaid: {
      conversation: "Nur der Chat. Die Bereiche bleiben, wo sie waren",
      code: "Dateien und Änderungen rechts, Terminal unten",
      review: "Die Änderungen neben der Datei, die sie betreffen",
      preview: "Die Seite rechts, das Terminal über die ganze Breite",
      explore: "Die Karte neben dem Code",
    },
    kept: "Gespeichert",
    keepNow: "Diese Anordnung speichern",
    keepName: "Name",
    keptName: (n: number) => `Anordnung ${n}`,
    forget: (name: string) => `Vergessen ${name}`,
    changed: "Anordnung geändert",
    undo: "Rückgängig",
    keep: "Speichern",
    treeWidth: "Breite des Dateibaums",
    artifacts: "Artefakte",
    capabilities: "Fähigkeiten",
    news: "Neuigkeiten",
    tool: { files: "Dateien", changes: "Änderungen", map: "Karte", web: "Web", terminal: "Terminal", tasks: "Hintergrund" },
    toolSaid: {
      files: "Baum und Code des Projekts",
      changes: "Was sich seit dem letzten Commit geändert hat",
      map: "Wie das Projekt aufgeteilt ist und was wovon abhängt",
      web: "Seiten und lokale Server",
      terminal: "Eine Konsole im Projektordner",
      tasks: "Subagents und Befehle des Modells",
    },
    tools: "Werkzeuge",
    closeTab: (name: string) => `${name} schließen`,
    split: "Zwei gleichzeitig zeigen",
    widen: "Nur dies zeigen",
    dropPair: "Ablegen, um beide zu sehen",
    pairSize: "Größe der Teilung",
    openTool: "Ein Werkzeug öffnen",
    refresh: "Aktualisieren",
    fileTree: "Dateibaum",
    showSidebar: "Seitenleiste einblenden",
    hideSidebar: "Seitenleiste ausblenden",
    updateAvailable: (version: string) => `Update verfügbar: Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} verfügbar`,
    update: "Aktualisieren",
    minimize: "Minimieren",
    focusMode: "Fokusmodus",
    focusModeKeys: (keys: string) => `Fokusmodus · Sens ausblenden und aus jedem Fenster fragen (${keys})`,
    maximize: "Maximieren",
    restore: "Wiederherstellen",
    chooseFolder: "Wähle den Arbeitsordner",
  },
  ja: {
    sidebarWidth: "サイドバーの幅",
    dockSize: { start: "左パネルの幅", end: "右パネルの幅", bottom: "下パネルの高さ" },
    dock: { start: "左", end: "右", bottom: "下" },
    moveHint: "別の端へドラッグするか、Alt と矢印キー",
    arrange: "レイアウト",
    arrangeKeys: (keys: string) => `レイアウト (${keys})`,
    arrangeSaid: "タブをウィンドウの端へドラッグするか、次のいずれかから始めます。",
    sessions: "セッション",
    chat: "チャット",
    railSide: "サイドバー",
    wide: "下パネルを全幅に",
    closedTools: "閉じたツール",
    emptyDock: "ツールをドロップ",
    dropMove: "ドロップしてここへ移動",
    starts: "ここから始める",
    start: { conversation: "会話", code: "コード", review: "レビュー", preview: "プレビュー", explore: "探索" },
    startSaid: {
      conversation: "チャットのみ。パネルは元の場所で待機します",
      code: "右にファイルと変更、下にターミナル",
      review: "変更を対象ファイルの隣に",
      preview: "右にページ、全幅のターミナル",
      explore: "コードの隣にマップ",
    },
    kept: "保存済み",
    keepNow: "このレイアウトを保存",
    keepName: "名前",
    keptName: (n: number) => `レイアウト ${n}`,
    forget: (name: string) => `削除 ${name}`,
    changed: "レイアウトを変更しました",
    undo: "元に戻す",
    keep: "保存",
    treeWidth: "ファイルツリーの幅",
    artifacts: "アーティファクト",
    capabilities: "機能",
    news: "新機能",
    tool: { files: "ファイル", changes: "変更", map: "マップ", web: "Web", terminal: "ターミナル", tasks: "バックグラウンド" },
    toolSaid: {
      files: "プロジェクトのツリーとコード",
      changes: "前回のコミットとの差分",
      map: "プロジェクトの構成と依存関係",
      web: "ページとローカルサーバー",
      terminal: "プロジェクトフォルダーのシェル",
      tasks: "サブエージェントとモデルのコマンド",
    },
    tools: "ツール",
    closeTab: (name: string) => `${name} を閉じる`,
    split: "2つ同時に表示",
    widen: "これだけ表示",
    dropPair: "ドロップして両方を表示",
    pairSize: "分割のサイズ",
    openTool: "ツールを開く",
    refresh: "更新",
    fileTree: "ファイルツリー",
    showSidebar: "サイドバーを表示",
    hideSidebar: "サイドバーを非表示",
    updateAvailable: (version: string) => `アップデートがあります: Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} が利用可能`,
    update: "アップデート",
    minimize: "最小化",
    focusMode: "フォーカスモード",
    focusModeKeys: (keys: string) => `フォーカスモード · Sens を隠して、どのウィンドウからでも質問する (${keys})`,
    maximize: "最大化",
    restore: "元のサイズに戻す",
    chooseFolder: "作業フォルダーを選択",
  },
  zh: {
    sidebarWidth: "侧边栏宽度",
    dockSize: { start: "左侧面板宽度", end: "右侧面板宽度", bottom: "底部面板高度" },
    dock: { start: "左侧", end: "右侧", bottom: "底部" },
    moveHint: "拖到另一侧，或按 Alt 加方向键",
    arrange: "布局",
    arrangeKeys: (keys: string) => `布局 (${keys})`,
    arrangeSaid: "把标签拖到窗口边缘，或从以下布局开始。",
    sessions: "会话",
    chat: "聊天",
    railSide: "侧边栏",
    wide: "底部面板占满宽度",
    closedTools: "已关闭",
    emptyDock: "拖入工具",
    dropMove: "松开即可移到这里",
    starts: "从这里开始",
    start: { conversation: "对话", code: "编码", review: "审阅", preview: "预览", explore: "探索" },
    startSaid: {
      conversation: "只有聊天，面板留在原处",
      code: "右侧是文件和更改，下方是终端",
      review: "更改紧挨着它们涉及的文件",
      preview: "右侧是页面，终端占满底部",
      explore: "地图紧挨着代码",
    },
    kept: "已保存",
    keepNow: "保存此布局",
    keepName: "名称",
    keptName: (n: number) => `布局 ${n}`,
    forget: (name: string) => `删除 ${name}`,
    changed: "布局已更改",
    undo: "撤销",
    keep: "保存",
    treeWidth: "文件树宽度",
    artifacts: "工件",
    capabilities: "能力",
    news: "新功能",
    tool: { files: "文件", changes: "更改", map: "地图", web: "网页", terminal: "终端", tasks: "后台" },
    toolSaid: {
      files: "项目的文件树和代码",
      changes: "与上次提交的差异",
      map: "项目的结构以及依赖关系",
      web: "网页和本地服务器",
      terminal: "项目文件夹中的 Shell",
      tasks: "子代理和模型运行的命令",
    },
    tools: "工具",
    closeTab: (name: string) => `关闭${name}`,
    split: "同时显示两个",
    widen: "仅显示此项",
    dropPair: "放下以同时显示两者",
    pairSize: "分割大小",
    openTool: "打开工具",
    refresh: "刷新",
    fileTree: "文件树",
    showSidebar: "显示侧边栏",
    hideSidebar: "隐藏侧边栏",
    updateAvailable: (version: string) => `有可用更新：Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} 可用`,
    update: "更新",
    minimize: "最小化",
    focusMode: "专注模式",
    focusModeKeys: (keys: string) => `专注模式 · 隐藏 Sens，在任何窗口中提问 (${keys})`,
    maximize: "最大化",
    restore: "还原",
    chooseFolder: "选择工作文件夹",
  },
});
