import { copy } from "../shared/i18n";

export const t = copy({
  en: {
    sidebarWidth: "Sidebar width",
    toolsWidth: "Tools panel width",
    treeWidth: "File tree width",
    artifacts: "Artifacts",
    capabilities: "Capabilities",
    news: "What’s new",
    tool: { files: "Files", changes: "Changes", map: "Map", web: "Web", terminal: "Terminal", tasks: "Background" },
    toolSaid: {
      files: "The project’s tree and code",
      changes: "What differs from the last commit",
      map: "How the project is laid out and what depends on what",
      web: "Pages and local servers",
      terminal: "A shell in the project folder",
      tasks: "Subagents and the model’s commands",
    },
    tools: "Tools",
    closeTab: (name: string) => `Close ${name}`,
    openTool: "Open a tool",
    refresh: "Refresh",
    fileTree: "File tree",
    showSidebar: "Show sidebar",
    hideSidebar: "Hide sidebar",
    updateAvailable: (version: string) => `Update available: Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} available`,
    update: "Update",
    minimize: "Minimize",
    focusMode: "Focus mode",
    focusModeKeys: (keys: string) => `Focus mode · Hide Sens and ask it from any window (${keys})`,
    maximize: "Maximize",
    restore: "Restore",
    chooseFolder: "Choose a working folder",
  },
  es: {
    sidebarWidth: "Ancho de la barra lateral",
    toolsWidth: "Ancho del panel de herramientas",
    treeWidth: "Ancho del árbol de ficheros",
    artifacts: "Artefactos",
    capabilities: "Capacidades",
    news: "Novedades",
    tool: { files: "Ficheros", changes: "Cambios", map: "Mapa", web: "Web", terminal: "Terminal", tasks: "Segundo plano" },
    toolSaid: {
      files: "El árbol y el código del proyecto",
      changes: "Lo que difiere del último commit",
      map: "Cómo se reparte el proyecto y qué depende de qué",
      web: "Páginas y servidores locales",
      terminal: "Una consola en la carpeta del proyecto",
      tasks: "Subagentes y comandos del modelo",
    },
    tools: "Herramientas",
    closeTab: (name: string) => `Cerrar ${name}`,
    openTool: "Abrir una herramienta",
    refresh: "Actualizar",
    fileTree: "Árbol de ficheros",
    showSidebar: "Mostrar la barra lateral",
    hideSidebar: "Ocultar la barra lateral",
    updateAvailable: (version: string) => `Actualización disponible: Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} disponible`,
    update: "Actualizar",
    minimize: "Minimizar",
    focusMode: "Modo focus",
    focusModeKeys: (keys: string) => `Modo focus · Oculta Sens y pregúntale desde cualquier ventana (${keys})`,
    maximize: "Maximizar",
    restore: "Restaurar",
    chooseFolder: "Elige la carpeta de trabajo",
  },
  fr: {
    sidebarWidth: "Largeur de la barre latérale",
    toolsWidth: "Largeur du panneau d’outils",
    treeWidth: "Largeur de l’arborescence",
    artifacts: "Artefacts",
    capabilities: "Capacités",
    news: "Nouveautés",
    tool: { files: "Fichiers", changes: "Modifications", map: "Carte", web: "Web", terminal: "Terminal", tasks: "Arrière-plan" },
    toolSaid: {
      files: "L’arborescence et le code du projet",
      changes: "Ce qui diffère du dernier commit",
      map: "Comment le projet est organisé et ce qui dépend de quoi",
      web: "Pages et serveurs locaux",
      terminal: "Une console dans le dossier du projet",
      tasks: "Sous-agents et commandes du modèle",
    },
    tools: "Outils",
    closeTab: (name: string) => `Fermer ${name}`,
    openTool: "Ouvrir un outil",
    refresh: "Actualiser",
    fileTree: "Arborescence des fichiers",
    showSidebar: "Afficher la barre latérale",
    hideSidebar: "Masquer la barre latérale",
    updateAvailable: (version: string) => `Mise à jour disponible : Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} disponible`,
    update: "Mettre à jour",
    minimize: "Réduire",
    focusMode: "Mode focus",
    focusModeKeys: (keys: string) => `Mode focus · Masquer Sens et lui demander depuis n’importe quelle fenêtre (${keys})`,
    maximize: "Agrandir",
    restore: "Restaurer",
    chooseFolder: "Choisissez le dossier de travail",
  },
  de: {
    sidebarWidth: "Breite der Seitenleiste",
    toolsWidth: "Breite des Werkzeugbereichs",
    treeWidth: "Breite des Dateibaums",
    artifacts: "Artefakte",
    capabilities: "Fähigkeiten",
    news: "Neuigkeiten",
    tool: { files: "Dateien", changes: "Änderungen", map: "Karte", web: "Web", terminal: "Terminal", tasks: "Hintergrund" },
    toolSaid: {
      files: "Baum und Code des Projekts",
      changes: "Was sich seit dem letzten Commit geändert hat",
      map: "Wie das Projekt aufgeteilt ist und was wovon abhängt",
      web: "Seiten und lokale Server",
      terminal: "Eine Konsole im Projektordner",
      tasks: "Subagents und Befehle des Modells",
    },
    tools: "Werkzeuge",
    closeTab: (name: string) => `${name} schließen`,
    openTool: "Ein Werkzeug öffnen",
    refresh: "Aktualisieren",
    fileTree: "Dateibaum",
    showSidebar: "Seitenleiste einblenden",
    hideSidebar: "Seitenleiste ausblenden",
    updateAvailable: (version: string) => `Update verfügbar: Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} verfügbar`,
    update: "Aktualisieren",
    minimize: "Minimieren",
    focusMode: "Fokusmodus",
    focusModeKeys: (keys: string) => `Fokusmodus · Sens ausblenden und aus jedem Fenster fragen (${keys})`,
    maximize: "Maximieren",
    restore: "Wiederherstellen",
    chooseFolder: "Wähle den Arbeitsordner",
  },
  ja: {
    sidebarWidth: "サイドバーの幅",
    toolsWidth: "ツールパネルの幅",
    treeWidth: "ファイルツリーの幅",
    artifacts: "アーティファクト",
    capabilities: "機能",
    news: "新機能",
    tool: { files: "ファイル", changes: "変更", map: "マップ", web: "Web", terminal: "ターミナル", tasks: "バックグラウンド" },
    toolSaid: {
      files: "プロジェクトのツリーとコード",
      changes: "前回のコミットとの差分",
      map: "プロジェクトの構成と依存関係",
      web: "ページとローカルサーバー",
      terminal: "プロジェクトフォルダーのシェル",
      tasks: "サブエージェントとモデルのコマンド",
    },
    tools: "ツール",
    closeTab: (name: string) => `${name} を閉じる`,
    openTool: "ツールを開く",
    refresh: "更新",
    fileTree: "ファイルツリー",
    showSidebar: "サイドバーを表示",
    hideSidebar: "サイドバーを非表示",
    updateAvailable: (version: string) => `アップデートがあります: Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} が利用可能`,
    update: "アップデート",
    minimize: "最小化",
    focusMode: "フォーカスモード",
    focusModeKeys: (keys: string) => `フォーカスモード · Sens を隠して、どのウィンドウからでも質問する (${keys})`,
    maximize: "最大化",
    restore: "元のサイズに戻す",
    chooseFolder: "作業フォルダーを選択",
  },
  zh: {
    sidebarWidth: "侧边栏宽度",
    toolsWidth: "工具面板宽度",
    treeWidth: "文件树宽度",
    artifacts: "工件",
    capabilities: "能力",
    news: "新功能",
    tool: { files: "文件", changes: "更改", map: "地图", web: "网页", terminal: "终端", tasks: "后台" },
    toolSaid: {
      files: "项目的文件树和代码",
      changes: "与上次提交的差异",
      map: "项目的结构以及依赖关系",
      web: "网页和本地服务器",
      terminal: "项目文件夹中的 Shell",
      tasks: "子代理和模型运行的命令",
    },
    tools: "工具",
    closeTab: (name: string) => `关闭${name}`,
    openTool: "打开工具",
    refresh: "刷新",
    fileTree: "文件树",
    showSidebar: "显示侧边栏",
    hideSidebar: "隐藏侧边栏",
    updateAvailable: (version: string) => `有可用更新：Sens ${version}`,
    versionAvailable: (version: string) => `Sens ${version} 可用`,
    update: "更新",
    minimize: "最小化",
    focusMode: "专注模式",
    focusModeKeys: (keys: string) => `专注模式 · 隐藏 Sens，在任何窗口中提问 (${keys})`,
    maximize: "最大化",
    restore: "还原",
    chooseFolder: "选择工作文件夹",
  },
});
