import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    sens: "Sens",
    found: (names: string) => `already has ${names}`,
    stopped: {
      write: "stopped a write",
      shell: "stopped a command",
      landed: "stopped a change",
      commit: "stopped a commit",
      blocked: "sent the changes back to Claude",
      close: "sent the changes back to Claude",
      reviewed: "sent the changes back to Claude",
    } as Record<string, string>,
    noted: (count: number) => (count === 1 ? "noted 1 thing" : `noted ${count} things`),
    reviewed: "reviewed the changes",
    passed: "approved the changes",
    pending: "waits for background work to finish",
    detached: "could not watch these changes",
    rules: {
      R1: "Copies existing code",
      R2: "Nearly copies existing code",
      R3: "New dependency",
      R4: "Leaves code unused",
      R5: "Grows the project",
      R6: "Comment in the code",
      R7: "Protected file",
      R8: "Removes tests",
      S1: "Abstraction with a single use",
      S2: "Fixes the symptom, not the cause",
      S3: "Rewrites what the platform or a dependency gives",
      S4: "Something nobody asked for",
      S5: "Clever where plain was enough",
      S6: "Removes a safeguard",
      S7: "Rewrites what the project has",
    } as Record<string, string>,
    uses: (count: number) => (count === 1 ? "used once" : `used ${count} times`),
    existing: "Already in the project",
    tally: (parts: string) => `Sens: ${parts}`,
    reused: (count: number) => `${count} reused`,
    stops: (count: number) => (count === 1 ? "1 stop" : `${count} stops`),
    approved: "approved",
    held: "held",
    heldTitle: "Sens does not approve these changes",
    unjudgedTitle: "Sens could not judge these changes",
    heldLead: "Claude tried three times. The changes stay on disk until you decide.",
    unjudgedLead: "The changes stay on disk until Sens judges them or you decide.",
    fix: "Ask Claude to fix them",
    undo: "Undo",
    accept: "Accept",
    retry: "Judge again",
    fixing: "Asked Claude to fix them",
    accepted: "Accepted · saved as exceptions of this project",
    undone: (count: number) => (count === 1 ? "Undone · 1 file restored" : `Undone · ${count} files restored`),
    kept: (count: number) => (count === 1 ? "1 file kept because you edited it" : `${count} files kept because you edited them`),
    retrying: "Judging again…",
    resolved: "Resolved",
    dependencyTitle: "Sens asks about a new dependency",
    testsTitle: "Sens asks about removed tests",
    canonTitle: "Sens asks before going on",
    dependencyLead: "Claude added it to the project’s manifest.",
    testsLead: "Claude removed tests or checks in this file.",
  },
  es: {
    sens: "Sens",
    found: (names: string) => `ya tiene ${names}`,
    stopped: {
      write: "paró una escritura",
      shell: "paró un comando",
      landed: "paró un cambio",
      commit: "paró un commit",
      blocked: "devolvió los cambios a Claude",
      close: "devolvió los cambios a Claude",
      reviewed: "devolvió los cambios a Claude",
    },
    noted: (count: number) => (count === 1 ? "anotó 1 cosa" : `anotó ${count} cosas`),
    reviewed: "revisó los cambios",
    passed: "aprobó los cambios",
    pending: "espera a que termine el trabajo en segundo plano",
    detached: "no pudo vigilar estos cambios",
    rules: {
      R1: "Copia código que ya existe",
      R2: "Casi copia código que ya existe",
      R3: "Dependencia nueva",
      R4: "Deja código sin usar",
      R5: "Hace crecer el proyecto",
      R6: "Comentario en el código",
      R7: "Fichero protegido",
      R8: "Quita tests",
      S1: "Abstracción con un solo uso",
      S2: "Arregla el síntoma, no la causa",
      S3: "Reescribe lo que da la plataforma o una dependencia",
      S4: "Algo que nadie pidió",
      S5: "Ingenio donde bastaba lo evidente",
      S6: "Quita una protección",
      S7: "Reescribe lo que el proyecto ya tiene",
    },
    uses: (count: number) => (count === 1 ? "usado 1 vez" : `usado ${count} veces`),
    existing: "Ya en el proyecto",
    tally: (parts: string) => `Sens: ${parts}`,
    reused: (count: number) => (count === 1 ? "1 reutilizado" : `${count} reutilizados`),
    stops: (count: number) => (count === 1 ? "1 parada" : `${count} paradas`),
    approved: "aprobado",
    held: "retenido",
    heldTitle: "Sens no aprueba estos cambios",
    unjudgedTitle: "Sens no pudo juzgar estos cambios",
    heldLead: "Claude lo intentó tres veces. Los cambios siguen en el disco hasta que decidas.",
    unjudgedLead: "Los cambios siguen en el disco hasta que Sens los juzgue o decidas tú.",
    fix: "Pedir que los arregle",
    undo: "Deshacer",
    accept: "Aceptar",
    retry: "Revisar otra vez",
    fixing: "Pedido el arreglo a Claude",
    accepted: "Aceptado · guardado como excepciones del proyecto",
    undone: (count: number) => (count === 1 ? "Deshecho · 1 fichero restaurado" : `Deshecho · ${count} ficheros restaurados`),
    kept: (count: number) => (count === 1 ? "1 fichero se queda porque lo editaste" : `${count} ficheros se quedan porque los editaste`),
    retrying: "Revisando otra vez…",
    resolved: "Resuelto",
    dependencyTitle: "Sens pregunta por una dependencia nueva",
    testsTitle: "Sens pregunta por tests quitados",
    canonTitle: "Sens pregunta antes de seguir",
    dependencyLead: "Claude la añadió al manifiesto del proyecto.",
    testsLead: "Claude quitó tests o comprobaciones en este fichero.",
  },
  fr: {
    sens: "Sens",
    found: (names: string) => `a déjà ${names}`,
    stopped: {
      write: "a arrêté une écriture",
      shell: "a arrêté une commande",
      landed: "a arrêté une modification",
      commit: "a arrêté un commit",
      blocked: "a renvoyé les modifications à Claude",
      close: "a renvoyé les modifications à Claude",
      reviewed: "a renvoyé les modifications à Claude",
    },
    noted: (count: number) => (count === 1 ? "a noté 1 point" : `a noté ${count} points`),
    reviewed: "a relu les modifications",
    passed: "a approuvé les modifications",
    pending: "attend la fin du travail en arrière-plan",
    detached: "n’a pas pu surveiller ces modifications",
    rules: {
      R1: "Copie du code existant",
      R2: "Copie presque du code existant",
      R3: "Nouvelle dépendance",
      R4: "Laisse du code inutilisé",
      R5: "Fait grossir le projet",
      R6: "Commentaire dans le code",
      R7: "Fichier protégé",
      R8: "Retire des tests",
      S1: "Abstraction à usage unique",
      S2: "Corrige le symptôme, pas la cause",
      S3: "Réécrit ce que donne la plateforme ou une dépendance",
      S4: "Quelque chose que personne n’a demandé",
      S5: "Astucieux là où l’évidence suffisait",
      S6: "Retire une protection",
      S7: "Réécrit ce que le projet a déjà",
    },
    uses: (count: number) => (count === 1 ? "utilisé 1 fois" : `utilisé ${count} fois`),
    existing: "Déjà dans le projet",
    tally: (parts: string) => `Sens : ${parts}`,
    reused: (count: number) => (count === 1 ? "1 réutilisé" : `${count} réutilisés`),
    stops: (count: number) => (count === 1 ? "1 arrêt" : `${count} arrêts`),
    approved: "approuvé",
    held: "retenu",
    heldTitle: "Sens n’approuve pas ces modifications",
    unjudgedTitle: "Sens n’a pas pu juger ces modifications",
    heldLead: "Claude a essayé trois fois. Les modifications restent sur le disque jusqu’à votre décision.",
    unjudgedLead: "Les modifications restent sur le disque jusqu’à ce que Sens les juge ou que vous décidiez.",
    fix: "Demander la correction",
    undo: "Annuler",
    accept: "Accepter",
    retry: "Juger à nouveau",
    fixing: "Correction demandée à Claude",
    accepted: "Accepté · enregistré comme exceptions du projet",
    undone: (count: number) => (count === 1 ? "Annulé · 1 fichier restauré" : `Annulé · ${count} fichiers restaurés`),
    kept: (count: number) => (count === 1 ? "1 fichier conservé car vous l’avez modifié" : `${count} fichiers conservés car vous les avez modifiés`),
    retrying: "Nouveau jugement…",
    resolved: "Réglé",
    dependencyTitle: "Sens demande pour une nouvelle dépendance",
    testsTitle: "Sens demande pour des tests retirés",
    canonTitle: "Sens demande avant de continuer",
    dependencyLead: "Claude l’a ajoutée au manifeste du projet.",
    testsLead: "Claude a retiré des tests ou des vérifications dans ce fichier.",
  },
  de: {
    sens: "Sens",
    found: (names: string) => `hat schon ${names}`,
    stopped: {
      write: "hat einen Schreibvorgang gestoppt",
      shell: "hat einen Befehl gestoppt",
      landed: "hat eine Änderung gestoppt",
      commit: "hat einen Commit gestoppt",
      blocked: "hat die Änderungen an Claude zurückgegeben",
      close: "hat die Änderungen an Claude zurückgegeben",
      reviewed: "hat die Änderungen an Claude zurückgegeben",
    },
    noted: (count: number) => (count === 1 ? "hat 1 Hinweis notiert" : `hat ${count} Hinweise notiert`),
    reviewed: "hat die Änderungen geprüft",
    passed: "hat die Änderungen freigegeben",
    pending: "wartet, bis die Hintergrundarbeit fertig ist",
    detached: "konnte diese Änderungen nicht überwachen",
    rules: {
      R1: "Kopiert vorhandenen Code",
      R2: "Kopiert vorhandenen Code fast",
      R3: "Neue Abhängigkeit",
      R4: "Lässt Code ungenutzt",
      R5: "Lässt das Projekt wachsen",
      R6: "Kommentar im Code",
      R7: "Geschützte Datei",
      R8: "Entfernt Tests",
      S1: "Abstraktion mit nur einer Verwendung",
      S2: "Behebt das Symptom, nicht die Ursache",
      S3: "Schreibt neu, was die Plattform oder eine Abhängigkeit bietet",
      S4: "Etwas, das niemand verlangt hat",
      S5: "Raffiniert, wo das Offensichtliche gereicht hätte",
      S6: "Entfernt eine Schutzmaßnahme",
      S7: "Schreibt neu, was das Projekt schon hat",
    },
    uses: (count: number) => (count === 1 ? "1-mal verwendet" : `${count}-mal verwendet`),
    existing: "Schon im Projekt",
    tally: (parts: string) => `Sens: ${parts}`,
    reused: (count: number) => `${count} wiederverwendet`,
    stops: (count: number) => (count === 1 ? "1 Stopp" : `${count} Stopps`),
    approved: "freigegeben",
    held: "zurückgehalten",
    heldTitle: "Sens gibt diese Änderungen nicht frei",
    unjudgedTitle: "Sens konnte diese Änderungen nicht beurteilen",
    heldLead: "Claude hat es dreimal versucht. Die Änderungen bleiben auf der Festplatte, bis du entscheidest.",
    unjudgedLead: "Die Änderungen bleiben auf der Festplatte, bis Sens sie beurteilt oder du entscheidest.",
    fix: "Um Korrektur bitten",
    undo: "Rückgängig machen",
    accept: "Akzeptieren",
    retry: "Erneut beurteilen",
    fixing: "Korrektur bei Claude angefordert",
    accepted: "Akzeptiert · als Ausnahmen des Projekts gespeichert",
    undone: (count: number) => (count === 1 ? "Rückgängig gemacht · 1 Datei wiederhergestellt" : `Rückgängig gemacht · ${count} Dateien wiederhergestellt`),
    kept: (count: number) => (count === 1 ? "1 Datei bleibt, weil du sie bearbeitet hast" : `${count} Dateien bleiben, weil du sie bearbeitet hast`),
    retrying: "Wird erneut beurteilt…",
    resolved: "Erledigt",
    dependencyTitle: "Sens fragt nach einer neuen Abhängigkeit",
    testsTitle: "Sens fragt nach entfernten Tests",
    canonTitle: "Sens fragt, bevor es weitergeht",
    dependencyLead: "Claude hat sie zum Manifest des Projekts hinzugefügt.",
    testsLead: "Claude hat in dieser Datei Tests oder Prüfungen entfernt.",
  },
  ja: {
    sens: "Sens",
    found: (names: string) => `既に ${names} があります`,
    stopped: {
      write: "書き込みを止めました",
      shell: "コマンドを止めました",
      landed: "変更を止めました",
      commit: "コミットを止めました",
      blocked: "変更を Claude に差し戻しました",
      close: "変更を Claude に差し戻しました",
      reviewed: "変更を Claude に差し戻しました",
    },
    noted: (count: number) => `${count} 件のメモを残しました`,
    reviewed: "変更をレビューしました",
    passed: "変更を承認しました",
    pending: "バックグラウンドの作業が終わるのを待っています",
    detached: "これらの変更を見守れませんでした",
    rules: {
      R1: "既存のコードをコピーしています",
      R2: "既存のコードをほぼコピーしています",
      R3: "新しい依存関係",
      R4: "使われないコードを残しています",
      R5: "プロジェクトを大きくしています",
      R6: "コード内のコメント",
      R7: "保護されたファイル",
      R8: "テストを削除しています",
      S1: "一度しか使われない抽象化",
      S2: "原因ではなく症状を直しています",
      S3: "プラットフォームや依存関係にあるものを書き直しています",
      S4: "誰も頼んでいないもの",
      S5: "素直な書き方で足りるところを凝っています",
      S6: "安全策を取り除いています",
      S7: "プロジェクトに既にあるものを書き直しています",
    },
    uses: (count: number) => `${count} 回使用`,
    existing: "既にプロジェクトにあります",
    tally: (parts: string) => `Sens: ${parts}`,
    reused: (count: number) => `${count} 件を再利用`,
    stops: (count: number) => `${count} 回停止`,
    approved: "承認済み",
    held: "保留",
    heldTitle: "Sens はこれらの変更を承認しません",
    unjudgedTitle: "Sens はこれらの変更を判断できませんでした",
    heldLead: "Claude は 3 回試しました。決めるまで変更はディスクに残ります。",
    unjudgedLead: "Sens が判断するか、あなたが決めるまで、変更はディスクに残ります。",
    fix: "修正を依頼",
    undo: "元に戻す",
    accept: "承認",
    retry: "もう一度判断",
    fixing: "Claude に修正を依頼しました",
    accepted: "承認済み · このプロジェクトの例外として保存しました",
    undone: (count: number) => `元に戻しました · ${count} 個のファイルを復元`,
    kept: (count: number) => `${count} 個のファイルはあなたが編集したため残しました`,
    retrying: "もう一度判断しています…",
    resolved: "解決済み",
    dependencyTitle: "Sens が新しい依存関係について確認しています",
    testsTitle: "Sens が削除されたテストについて確認しています",
    canonTitle: "Sens が続ける前に確認しています",
    dependencyLead: "Claude がプロジェクトのマニフェストに追加しました。",
    testsLead: "Claude がこのファイルのテストやチェックを削除しました。",
  },
  zh: {
    sens: "Sens",
    found: (names: string) => `已有 ${names}`,
    stopped: {
      write: "阻止了一次写入",
      shell: "阻止了一条命令",
      landed: "阻止了一次更改",
      commit: "阻止了一次提交",
      blocked: "把更改退回给了 Claude",
      close: "把更改退回给了 Claude",
      reviewed: "把更改退回给了 Claude",
    },
    noted: (count: number) => `记录了 ${count} 条提示`,
    reviewed: "审查了这些更改",
    passed: "批准了这些更改",
    pending: "正在等待后台任务完成",
    detached: "未能监督这些更改",
    rules: {
      R1: "复制了已有代码",
      R2: "几乎复制了已有代码",
      R3: "新依赖",
      R4: "留下了未使用的代码",
      R5: "让项目变大",
      R6: "代码中的注释",
      R7: "受保护的文件",
      R8: "删除了测试",
      S1: "只用一次的抽象",
      S2: "治标不治本",
      S3: "重写了平台或依赖已提供的功能",
      S4: "没人要求的东西",
      S5: "本可以直白却写得取巧",
      S6: "去掉了一道防护",
      S7: "重写了项目里已有的东西",
    },
    uses: (count: number) => `使用 ${count} 次`,
    existing: "项目中已有",
    tally: (parts: string) => `Sens：${parts}`,
    reused: (count: number) => `复用 ${count} 处`,
    stops: (count: number) => `拦截 ${count} 次`,
    approved: "已批准",
    held: "已暂扣",
    heldTitle: "Sens 不批准这些更改",
    unjudgedTitle: "Sens 无法评判这些更改",
    heldLead: "Claude 已尝试三次。在你决定之前，更改会保留在磁盘上。",
    unjudgedLead: "在 Sens 评判或你决定之前，更改会保留在磁盘上。",
    fix: "请 Claude 修复",
    undo: "撤销",
    accept: "接受",
    retry: "重新评判",
    fixing: "已请 Claude 修复",
    accepted: "已接受 · 已保存为本项目的例外",
    undone: (count: number) => `已撤销 · 已恢复 ${count} 个文件`,
    kept: (count: number) => `${count} 个文件因你编辑过而保留`,
    retrying: "正在重新评判…",
    resolved: "已处理",
    dependencyTitle: "Sens 询问是否添加新依赖",
    testsTitle: "Sens 询问被删除的测试",
    canonTitle: "Sens 在继续之前询问",
    dependencyLead: "Claude 已将其加入项目清单。",
    testsLead: "Claude 删除了此文件中的测试或检查。",
  },
});
