[env]
GGML_NATIVE = "OFF"
GGML_AVX = "ON"
GGML_AVX2 = "ON"
GGML_FMA = "ON"
GGML_F16C = "ON"
GGML_AVX512 = "OFF"
CMAKE_C_FLAGS_RELEASE = "-nologo -MD -Brepro -W0 /O2 /Ob2 /DNDEBUG"
CMAKE_CXX_FLAGS_RELEASE = "/utf-8 -nologo -MD -Brepro -W0 /O2 /Ob2 /DNDEBUG"
CMAKE_C_FLAGS_RELWITHDEBINFO = "-nologo -MD -Brepro -W0 /O2 /Ob1 /DNDEBUG"
CMAKE_CXX_FLAGS_RELWITHDEBINFO = "/utf-8 -nologo -MD -Brepro -W0 /O2 /Ob1 /DNDEBUG"
