import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    chooseFolderTitle: "Choose a working folder",
    chooseFolder: "Choose folder…",
    uncommitted: (count: number) => (count === 1 ? "1 uncommitted file" : `${count} uncommitted files`),
    detached: (branch: string) => `Detached HEAD at ${branch}`,
    isolateHelp: "Works on a separate copy of the repository, on a new branch: nothing Claude does touches your folder until you merge it.",
    worktreeTitle: (branch: string, base: string, path: string) => `Works in a separate worktree, on branch ${branch} (created from ${base}): ${path}`,
    worktreeChip: "worktree",
    worktreeToggle: "Worktree",
    searchBranches: "Search branches…",
    noBranchMatch: "No branch matches.",
    noOtherBranch: "No other branches.",
    branchSwitched: "branch · ",
    send: "Send",
    stop: "Stop",
    stopping: "Stopping…",
    attach: "Attach files",
    attachDialog: "Attach files or pictures",
    dictate: "Dictate",
    stopDictating: "Stop dictating",
    transcribing: "Transcribing…",
    voiceFetching: (percent: number) => `Getting the voice model ready · ${percent}%`,
    voiceFetchingStarts: "Sens is downloading its voice model, once · dictation will be ready in a moment",
    microphoneRefused: (reason: string) => `${reason} · choose the microphone in Settings › General › Voice`,
    placeholder: "Ask for anything · @ for a file, / for a command",
    messageLabel: "Message for Claude",
    projectFiles: "Project files",
    claudeCommands: "Claude Code commands",
    attachments: "Attachments",
    dropHere: "Drop to attach",
    folder: "Folder",
    file: "File",
    items: (count: number) => (count === 1 ? "1 item" : `${count} items`),
    pastedText: "Pasted text",
    lines: (count: number) => (count === 1 ? "1 line" : `${count} lines`),
    asText: "Paste as text",
    seePicture: (name: string) => `View ${name}`,
    openFile: (name: string) => `Open ${name}`,
    pastedPicture: "pasted picture",
    pastedFile: "pasted file",
    converted: (from: string, to: string) => `converted from ${from} to ${to}`,
    reduced: (width: number, height: number) => `reduced to ${width}×${height}`,
    missing: (name: string) => `${name} doesn’t exist`,
    unreadable: (name: string) => `Couldn’t read ${name}`,
    tooBig: (name: string, most: number) => `${name} is over ${most} MB · files from outside the project are attached up to that size`,
    isProject: (name: string) => `${name} is the project folder · Claude already works in it`,
    tooManyPictures: (most: number) => `Up to ${most} pictures per message · the rest were left out`,
    tooManyFiles: (most: number) => `Up to ${most} attachments per message · the rest were left out`,
    stageFailed: (name: string, reason: string) => `Couldn’t attach ${name}: ${reason}`,
    change: {
      title: { model: "Switching models mid-session uses more of your plan", thinking: "Turning thinking on or off mid-session uses more of your plan", effort: "Changing the effort mid-session uses more of your plan", several: "These changes mid-session use more of your plan" },
      said: (before: string, after: string, tokens: string) =>
        `This session ran with ${before}. With ${after}, the next message reads the whole conversation${tokens ? ` (${tokens} tokens)` : ""} again without the cache, and that uses more of your plan. We recommend starting a new session.`,
      thinkingOn: "thinking on",
      thinkingOff: "thinking off",
      effortAt: (level: string) => `${level.toLowerCase()} effort`,
      newSession: "New session",
      undo: "Undo",
    },
  },
  es: {
    chooseFolderTitle: "Elegir carpeta de trabajo",
    chooseFolder: "Elegir carpeta…",
    uncommitted: (count: number) => (count === 1 ? "1 fichero sin confirmar" : `${count} ficheros sin confirmar`),
    detached: (branch: string) => `HEAD suelto en ${branch}`,
    isolateHelp: "Trabaja en una copia aparte del repositorio, en una rama nueva: lo que haga Claude no toca tu carpeta hasta que lo fusiones.",
    worktreeTitle: (branch: string, base: string, path: string) => `Trabaja en un worktree aparte, en la rama ${branch} (creada desde ${base}): ${path}`,
    worktreeChip: "worktree",
    worktreeToggle: "Worktree",
    searchBranches: "Buscar ramas…",
    noBranchMatch: "Ninguna rama coincide.",
    noOtherBranch: "No hay más ramas.",
    branchSwitched: "rama · ",
    send: "Enviar",
    stop: "Parar",
    stopping: "Parando…",
    attach: "Adjuntar ficheros",
    attachDialog: "Adjuntar ficheros o imágenes",
    dictate: "Dictar",
    stopDictating: "Parar el dictado",
    transcribing: "Transcribiendo…",
    voiceFetching: (percent: number) => `Preparando el modelo de voz · ${percent} %`,
    voiceFetchingStarts: "Sens está descargando su modelo de voz, una sola vez · el dictado estará listo en un momento",
    microphoneRefused: (reason: string) => `${reason} · elige el micrófono en Ajustes › General › Voz`,
    placeholder: "Pide lo que necesites · @ para un fichero, / para un comando",
    messageLabel: "Mensaje para Claude",
    projectFiles: "Ficheros del proyecto",
    claudeCommands: "Comandos de Claude Code",
    attachments: "Adjuntos",
    dropHere: "Suelta para adjuntar",
    folder: "Carpeta",
    file: "Fichero",
    items: (count: number) => (count === 1 ? "1 elemento" : `${count} elementos`),
    pastedText: "Texto pegado",
    lines: (count: number) => (count === 1 ? "1 línea" : `${count} líneas`),
    asText: "Pegar como texto",
    seePicture: (name: string) => `Ver ${name}`,
    openFile: (name: string) => `Abrir ${name}`,
    pastedPicture: "imagen pegada",
    pastedFile: "fichero pegado",
    converted: (from: string, to: string) => `convertida de ${from} a ${to}`,
    reduced: (width: number, height: number) => `reducida a ${width}×${height}`,
    missing: (name: string) => `${name} no existe`,
    unreadable: (name: string) => `No pude leer ${name}`,
    tooBig: (name: string, most: number) => `${name} pasa de ${most} MB · lo que viene de fuera del proyecto se adjunta hasta ese tamaño`,
    isProject: (name: string) => `${name} es la carpeta del proyecto · Claude ya trabaja en ella`,
    tooManyPictures: (most: number) => `Hasta ${most} imágenes por mensaje · el resto no se adjuntó`,
    tooManyFiles: (most: number) => `Hasta ${most} adjuntos por mensaje · el resto no se adjuntó`,
    stageFailed: (name: string, reason: string) => `No pude adjuntar ${name}: ${reason}`,
    change: {
      title: { model: "Cambiar de modelo a mitad de sesión gasta más de tu plan", thinking: "Cambiar el razonamiento a mitad de sesión gasta más de tu plan", effort: "Cambiar el esfuerzo a mitad de sesión gasta más de tu plan", several: "Estos cambios a mitad de sesión gastan más de tu plan" },
      said: (before: string, after: string, tokens: string) =>
        `Esta sesión iba con ${before}. Con ${after}, el próximo mensaje vuelve a leer toda la conversación${tokens ? ` (${tokens} tokens)` : ""} sin caché, y eso gasta más de tu plan. Te recomendamos empezar una sesión nueva.`,
      thinkingOn: "razonamiento activado",
      thinkingOff: "razonamiento desactivado",
      effortAt: (level: string) => `esfuerzo ${level.toLowerCase()}`,
      newSession: "Sesión nueva",
      undo: "Deshacer",
    },
  },
  fr: {
    chooseFolderTitle: "Choisir un dossier de travail",
    chooseFolder: "Choisir un dossier…",
    uncommitted: (count: number) => (count === 1 ? "1 fichier non validé" : `${count} fichiers non validés`),
    detached: (branch: string) => `HEAD détaché sur ${branch}`,
    isolateHelp: "Travaille sur une copie séparée du dépôt, dans une nouvelle branche : ce que fait Claude ne touche pas votre dossier tant que vous ne l’avez pas fusionné.",
    worktreeTitle: (branch: string, base: string, path: string) => `Travaille dans un worktree séparé, sur la branche ${branch} (créée depuis ${base}) : ${path}`,
    worktreeChip: "worktree",
    worktreeToggle: "Worktree",
    searchBranches: "Rechercher des branches…",
    noBranchMatch: "Aucune branche ne correspond.",
    noOtherBranch: "Aucune autre branche.",
    branchSwitched: "branche · ",
    send: "Envoyer",
    stop: "Arrêter",
    stopping: "Arrêt…",
    attach: "Joindre des fichiers",
    attachDialog: "Joindre des fichiers ou des images",
    dictate: "Dicter",
    stopDictating: "Arrêter la dictée",
    transcribing: "Transcription…",
    voiceFetching: (percent: number) => `Préparation du modèle vocal · ${percent} %`,
    voiceFetchingStarts: "Sens télécharge son modèle vocal, une seule fois · la dictée sera prête dans un instant",
    microphoneRefused: (reason: string) => `${reason} · choisissez le microphone dans Paramètres › Général › Voix`,
    placeholder: "Demandez ce dont vous avez besoin · @ pour un fichier, / pour une commande",
    messageLabel: "Message pour Claude",
    projectFiles: "Fichiers du projet",
    claudeCommands: "Commandes de Claude Code",
    attachments: "Pièces jointes",
    dropHere: "Déposez pour joindre",
    folder: "Dossier",
    file: "Fichier",
    items: (count: number) => (count <= 1 ? `${count} élément` : `${count} éléments`),
    pastedText: "Texte collé",
    lines: (count: number) => (count <= 1 ? `${count} ligne` : `${count} lignes`),
    asText: "Coller comme texte",
    seePicture: (name: string) => `Afficher ${name}`,
    openFile: (name: string) => `Ouvrir ${name}`,
    pastedPicture: "image collée",
    pastedFile: "fichier collé",
    converted: (from: string, to: string) => `convertie de ${from} en ${to}`,
    reduced: (width: number, height: number) => `réduite à ${width}×${height}`,
    missing: (name: string) => `${name} n’existe pas`,
    unreadable: (name: string) => `Impossible de lire ${name}`,
    tooBig: (name: string, most: number) => `${name} dépasse ${most} Mo · les fichiers extérieurs au projet sont joints jusqu’à cette taille`,
    isProject: (name: string) => `${name} est le dossier du projet · Claude y travaille déjà`,
    tooManyPictures: (most: number) => `Jusqu’à ${most} images par message · les autres n’ont pas été jointes`,
    tooManyFiles: (most: number) => `Jusqu’à ${most} pièces jointes par message · les autres n’ont pas été jointes`,
    stageFailed: (name: string, reason: string) => `Impossible de joindre ${name} : ${reason}`,
    change: {
      title: { model: "Changer de modèle en cours de session consomme davantage votre forfait", thinking: "Activer ou désactiver la réflexion en cours de session consomme davantage votre forfait", effort: "Changer l’effort en cours de session consomme davantage votre forfait", several: "Ces changements en cours de session consomment davantage votre forfait" },
      said: (before: string, after: string, tokens: string) =>
        `Cette session utilisait ${before}. Avec ${after}, le prochain message relit toute la conversation${tokens ? ` (${tokens} tokens)` : ""} sans cache, ce qui consomme davantage votre forfait. Nous vous conseillons de démarrer une nouvelle session.`,
      thinkingOn: "la réflexion activée",
      thinkingOff: "la réflexion désactivée",
      effortAt: (level: string) => `un effort ${level.toLowerCase()}`,
      newSession: "Nouvelle session",
      undo: "Annuler",
    },
  },
  de: {
    chooseFolderTitle: "Arbeitsordner wählen",
    chooseFolder: "Ordner wählen…",
    uncommitted: (count: number) => (count === 1 ? "1 nicht committete Datei" : `${count} nicht committete Dateien`),
    detached: (branch: string) => `Losgelöster HEAD bei ${branch}`,
    isolateHelp: "Arbeitet in einer separaten Kopie des Repositorys, auf einem neuen Branch: Was Claude tut, berührt deinen Ordner erst, wenn du es zusammenführst.",
    worktreeTitle: (branch: string, base: string, path: string) => `Arbeitet in einem separaten Worktree, auf dem Branch ${branch} (erstellt aus ${base}): ${path}`,
    worktreeChip: "Worktree",
    worktreeToggle: "Worktree",
    searchBranches: "Branches suchen…",
    noBranchMatch: "Kein passender Branch.",
    noOtherBranch: "Keine weiteren Branches.",
    branchSwitched: "Branch · ",
    send: "Senden",
    stop: "Stoppen",
    stopping: "Wird gestoppt…",
    attach: "Dateien anhängen",
    attachDialog: "Dateien oder Bilder anhängen",
    dictate: "Diktieren",
    stopDictating: "Diktat beenden",
    transcribing: "Wird transkribiert …",
    voiceFetching: (percent: number) => `Sprachmodell wird vorbereitet · ${percent} %`,
    voiceFetchingStarts: "Sens lädt sein Sprachmodell herunter, nur einmal · das Diktat ist gleich bereit",
    microphoneRefused: (reason: string) => `${reason} · wähle das Mikrofon unter Einstellungen › Allgemein › Sprache`,
    placeholder: "Frag, was du brauchst · @ für eine Datei, / für einen Befehl",
    messageLabel: "Nachricht an Claude",
    projectFiles: "Projektdateien",
    claudeCommands: "Befehle von Claude Code",
    attachments: "Anhänge",
    dropHere: "Zum Anhängen ablegen",
    folder: "Ordner",
    file: "Datei",
    items: (count: number) => (count === 1 ? "1 Element" : `${count} Elemente`),
    pastedText: "Eingefügter Text",
    lines: (count: number) => (count === 1 ? "1 Zeile" : `${count} Zeilen`),
    asText: "Als Text einfügen",
    seePicture: (name: string) => `${name} ansehen`,
    openFile: (name: string) => `${name} öffnen`,
    pastedPicture: "eingefügtes Bild",
    pastedFile: "eingefügte Datei",
    converted: (from: string, to: string) => `von ${from} in ${to} umgewandelt`,
    reduced: (width: number, height: number) => `auf ${width}×${height} verkleinert`,
    missing: (name: string) => `${name} existiert nicht`,
    unreadable: (name: string) => `${name} konnte nicht gelesen werden`,
    tooBig: (name: string, most: number) => `${name} ist größer als ${most} MB · Dateien von außerhalb des Projekts werden bis zu dieser Größe angehängt`,
    isProject: (name: string) => `${name} ist der Projektordner · Claude arbeitet bereits darin`,
    tooManyPictures: (most: number) => `Bis zu ${most} Bilder pro Nachricht · der Rest wurde nicht angehängt`,
    tooManyFiles: (most: number) => `Bis zu ${most} Anhänge pro Nachricht · der Rest wurde nicht angehängt`,
    stageFailed: (name: string, reason: string) => `${name} konnte nicht angehängt werden: ${reason}`,
    change: {
      title: { model: "Ein Modellwechsel mitten in der Sitzung verbraucht mehr von deinem Plan", thinking: "Denken mitten in der Sitzung ein- oder auszuschalten verbraucht mehr von deinem Plan", effort: "Den Aufwand mitten in der Sitzung zu ändern verbraucht mehr von deinem Plan", several: "Diese Änderungen mitten in der Sitzung verbrauchen mehr von deinem Plan" },
      said: (before: string, after: string, tokens: string) =>
        `Diese Sitzung lief mit ${before}. Mit ${after} liest die nächste Nachricht das ganze Gespräch${tokens ? ` (${tokens} Tokens)` : ""} ohne Cache neu ein und verbraucht dadurch mehr von deinem Plan. Wir empfehlen, eine neue Sitzung zu starten.`,
      thinkingOn: "eingeschaltetem Denken",
      thinkingOff: "ausgeschaltetem Denken",
      effortAt: (level: string) => `Aufwand „${level}“`,
      newSession: "Neue Sitzung",
      undo: "Rückgängig",
    },
  },
  ja: {
    chooseFolderTitle: "作業フォルダーを選択",
    chooseFolder: "フォルダーを選択…",
    uncommitted: (count: number) => `未コミットのファイル ${count} 個`,
    detached: (branch: string) => `${branch} で HEAD が切り離されています`,
    isolateHelp: "リポジトリの別コピーで、新しいブランチを使って作業します。マージするまで、Claude の作業は元のフォルダーに影響しません。",
    worktreeTitle: (branch: string, base: string, path: string) => `別のワークツリーのブランチ ${branch}（${base} から作成）で作業します: ${path}`,
    worktreeChip: "ワークツリー",
    worktreeToggle: "ワークツリー",
    searchBranches: "ブランチを検索…",
    noBranchMatch: "一致するブランチはありません。",
    noOtherBranch: "ほかのブランチはありません。",
    branchSwitched: "ブランチ · ",
    send: "送信",
    stop: "停止",
    stopping: "停止中…",
    attach: "ファイルを添付",
    attachDialog: "ファイルや画像を添付",
    dictate: "音声入力",
    stopDictating: "音声入力を停止",
    transcribing: "文字に起こしています…",
    voiceFetching: (percent: number) => `音声モデルを準備中 · ${percent}%`,
    voiceFetchingStarts: "Sens が音声モデルをダウンロードしています（初回のみ）· まもなく音声入力を使えます",
    microphoneRefused: (reason: string) => `${reason} · 設定 › 一般 › 音声 でマイクを選んでください`,
    placeholder: "必要なことを入力 · @ でファイル、/ でコマンド",
    messageLabel: "Claude へのメッセージ",
    projectFiles: "プロジェクトのファイル",
    claudeCommands: "Claude Code のコマンド",
    attachments: "添付ファイル",
    dropHere: "ドロップして添付",
    folder: "フォルダー",
    file: "ファイル",
    items: (count: number) => `${count} 個の項目`,
    pastedText: "貼り付けたテキスト",
    lines: (count: number) => `${count} 行`,
    asText: "テキストとして貼り付け",
    seePicture: (name: string) => `${name} を表示`,
    openFile: (name: string) => `${name} を開く`,
    pastedPicture: "貼り付けた画像",
    pastedFile: "貼り付けたファイル",
    converted: (from: string, to: string) => `${from} から ${to} に変換`,
    reduced: (width: number, height: number) => `${width}×${height} に縮小`,
    missing: (name: string) => `${name} は存在しません`,
    unreadable: (name: string) => `${name} を読み取れませんでした`,
    tooBig: (name: string, most: number) => `${name} は ${most} MB を超えています · プロジェクト外のファイルはこのサイズまで添付できます`,
    isProject: (name: string) => `${name} はプロジェクトフォルダーです · Claude はすでにその中で作業しています`,
    tooManyPictures: (most: number) => `画像は 1 メッセージにつき ${most} 枚までです · 残りは添付されませんでした`,
    tooManyFiles: (most: number) => `添付ファイルは 1 メッセージにつき ${most} 個までです · 残りは添付されませんでした`,
    stageFailed: (name: string, reason: string) => `${name} を添付できませんでした: ${reason}`,
    change: {
      title: { model: "セッションの途中でモデルを変えると、プランの消費が増えます", thinking: "セッションの途中で思考を切り替えると、プランの消費が増えます", effort: "セッションの途中で推論の強さを変えると、プランの消費が増えます", several: "セッションの途中でこれらを変えると、プランの消費が増えます" },
      said: (before: string, after: string, tokens: string) =>
        `このセッションは ${before} を使っていました。${after} に変えると、次のメッセージで会話全体${tokens ? `（${tokens} トークン）` : ""}をキャッシュなしで読み直すため、プランの消費が増えます。新しいセッションを始めることをおすすめします。`,
      thinkingOn: "思考オン",
      thinkingOff: "思考オフ",
      effortAt: (level: string) => `推論の強さ「${level}」`,
      newSession: "新しいセッション",
      undo: "元に戻す",
    },
  },
  zh: {
    chooseFolderTitle: "选择工作文件夹",
    chooseFolder: "选择文件夹…",
    uncommitted: (count: number) => `${count} 个未提交的文件`,
    detached: (branch: string) => `HEAD 已分离于 ${branch}`,
    isolateHelp: "在仓库的独立副本和新分支上工作：合并之前，Claude 的任何操作都不会影响你的文件夹。",
    worktreeTitle: (branch: string, base: string, path: string) => `在独立的工作树中工作，分支 ${branch}（从 ${base} 创建）：${path}`,
    worktreeChip: "工作树",
    worktreeToggle: "工作树",
    searchBranches: "搜索分支…",
    noBranchMatch: "没有匹配的分支。",
    noOtherBranch: "没有其他分支。",
    branchSwitched: "分支 · ",
    send: "发送",
    stop: "停止",
    stopping: "正在停止…",
    attach: "附加文件",
    attachDialog: "附加文件或图片",
    dictate: "语音输入",
    stopDictating: "停止语音输入",
    transcribing: "正在转写…",
    voiceFetching: (percent: number) => `正在准备语音模型 · ${percent}%`,
    voiceFetchingStarts: "Sens 正在下载语音模型（仅需一次）· 语音输入马上就能使用",
    microphoneRefused: (reason: string) => `${reason} · 请在 设置 › 通用 › 语音 中选择麦克风`,
    placeholder: "说出你的需求 · @ 引用文件，/ 使用命令",
    messageLabel: "发给 Claude 的消息",
    projectFiles: "项目文件",
    claudeCommands: "Claude Code 命令",
    attachments: "附件",
    dropHere: "松开即可附加",
    folder: "文件夹",
    file: "文件",
    items: (count: number) => `${count} 项`,
    pastedText: "粘贴的文本",
    lines: (count: number) => `${count} 行`,
    asText: "作为文本粘贴",
    seePicture: (name: string) => `查看 ${name}`,
    openFile: (name: string) => `打开 ${name}`,
    pastedPicture: "粘贴的图片",
    pastedFile: "粘贴的文件",
    converted: (from: string, to: string) => `已从 ${from} 转换为 ${to}`,
    reduced: (width: number, height: number) => `已缩小至 ${width}×${height}`,
    missing: (name: string) => `${name} 不存在`,
    unreadable: (name: string) => `无法读取 ${name}`,
    tooBig: (name: string, most: number) => `${name} 超过 ${most} MB · 项目外的文件最大可附加 ${most} MB`,
    isProject: (name: string) => `${name} 就是项目文件夹 · Claude 已在其中工作`,
    tooManyPictures: (most: number) => `每条消息最多 ${most} 张图片 · 其余未附加`,
    tooManyFiles: (most: number) => `每条消息最多 ${most} 个附件 · 其余未附加`,
    stageFailed: (name: string, reason: string) => `无法附加 ${name}：${reason}`,
    change: {
      title: { model: "在会话中途切换模型会消耗更多套餐用量", thinking: "在会话中途开关思考会消耗更多套餐用量", effort: "在会话中途调整推理强度会消耗更多套餐用量", several: "在会话中途做这些更改会消耗更多套餐用量" },
      said: (before: string, after: string, tokens: string) =>
        `此会话使用的是 ${before}。换成 ${after} 后，下一条消息会在没有缓存的情况下重新读取整个对话${tokens ? `（${tokens} 个 token）` : ""}，消耗更多套餐用量。建议开始一个新会话。`,
      thinkingOn: "开启思考",
      thinkingOff: "关闭思考",
      effortAt: (level: string) => `推理强度「${level}」`,
      newSession: "新会话",
      undo: "撤销",
    },
  },
});
