import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    noProject: "Open a project to see how Sens guards it.",
    rules: "Project rules",
    noComments: "No comments in the code",
    noCommentsNote: "Sens stops any comment Claude writes in this project.",
    exceptions: "Exceptions",
    exceptionsNote: "What you accepted no longer stops Claude. Retract it to be strict again.",
    noExceptions: "No exceptions.",
    retract: "Retract",
    avoided: "Last 30 days",
    nothingYet: "Sens has not stopped anything in this project yet.",
    copies: (count: number) => (count === 1 ? "1 copy stopped" : `${count} copies stopped`),
    dependencies: (count: number) => (count === 1 ? "1 dependency refused" : `${count} dependencies refused`),
    comments: (count: number) => (count === 1 ? "1 comment stopped" : `${count} comments stopped`),
    protectedFiles: (count: number) => (count === 1 ? "1 protected file kept" : `${count} protected files kept`),
    tests: (count: number) => (count === 1 ? "1 removal of tests stopped" : `${count} removals of tests stopped`),
    orphans: (count: number) => (count === 1 ? "1 piece of unused code stopped" : `${count} pieces of unused code stopped`),
    judgment: (count: number) => (count === 1 ? "1 reviewer finding" : `${count} reviewer findings`),
    held: (count: number) => (count === 1 ? "Held once" : `Held ${count} times`),
    reviews: (count: number, cost: string) => (count === 1 ? `1 review · ${cost}` : `${count} reviews · ${cost}`),
  },
  es: {
    noProject: "Abre un proyecto para ver cómo lo vigila Sens.",
    rules: "Normas del proyecto",
    noComments: "Sin comentarios en el código",
    noCommentsNote: "Sens para cualquier comentario que Claude escriba en este proyecto.",
    exceptions: "Excepciones",
    exceptionsNote: "Lo que aceptaste ya no para a Claude. Retíralo para volver a ser estricto.",
    noExceptions: "Sin excepciones.",
    retract: "Retirar",
    avoided: "Últimos 30 días",
    nothingYet: "Sens aún no ha parado nada en este proyecto.",
    copies: (count: number) => (count === 1 ? "1 copia parada" : `${count} copias paradas`),
    dependencies: (count: number) => (count === 1 ? "1 dependencia rechazada" : `${count} dependencias rechazadas`),
    comments: (count: number) => (count === 1 ? "1 comentario parado" : `${count} comentarios parados`),
    protectedFiles: (count: number) => (count === 1 ? "1 fichero protegido a salvo" : `${count} ficheros protegidos a salvo`),
    tests: (count: number) => (count === 1 ? "1 borrado de tests parado" : `${count} borrados de tests parados`),
    orphans: (count: number) => (count === 1 ? "1 código sin usar parado" : `${count} códigos sin usar parados`),
    judgment: (count: number) => (count === 1 ? "1 hallazgo del revisor" : `${count} hallazgos del revisor`),
    held: (count: number) => (count === 1 ? "Retenido 1 vez" : `Retenido ${count} veces`),
    reviews: (count: number, cost: string) => (count === 1 ? `1 revisión · ${cost}` : `${count} revisiones · ${cost}`),
  },
  fr: {
    noProject: "Ouvrez un projet pour voir comment Sens le surveille.",
    rules: "Règles du projet",
    noComments: "Aucun commentaire dans le code",
    noCommentsNote: "Sens arrête tout commentaire que Claude écrit dans ce projet.",
    exceptions: "Exceptions",
    exceptionsNote: "Ce que vous avez accepté n’arrête plus Claude. Retirez-le pour redevenir strict.",
    noExceptions: "Aucune exception.",
    retract: "Retirer",
    avoided: "30 derniers jours",
    nothingYet: "Sens n’a encore rien arrêté dans ce projet.",
    copies: (count: number) => (count === 1 ? "1 copie arrêtée" : `${count} copies arrêtées`),
    dependencies: (count: number) => (count === 1 ? "1 dépendance refusée" : `${count} dépendances refusées`),
    comments: (count: number) => (count === 1 ? "1 commentaire arrêté" : `${count} commentaires arrêtés`),
    protectedFiles: (count: number) => (count === 1 ? "1 fichier protégé préservé" : `${count} fichiers protégés préservés`),
    tests: (count: number) => (count === 1 ? "1 suppression de tests arrêtée" : `${count} suppressions de tests arrêtées`),
    orphans: (count: number) => (count === 1 ? "1 code inutilisé arrêté" : `${count} codes inutilisés arrêtés`),
    judgment: (count: number) => (count === 1 ? "1 constat du relecteur" : `${count} constats du relecteur`),
    held: (count: number) => (count === 1 ? "Retenu 1 fois" : `Retenu ${count} fois`),
    reviews: (count: number, cost: string) => (count === 1 ? `1 relecture · ${cost}` : `${count} relectures · ${cost}`),
  },
  de: {
    noProject: "Öffne ein Projekt, um zu sehen, wie Sens es überwacht.",
    rules: "Projektregeln",
    noComments: "Keine Kommentare im Code",
    noCommentsNote: "Sens stoppt jeden Kommentar, den Claude in diesem Projekt schreibt.",
    exceptions: "Ausnahmen",
    exceptionsNote: "Was du akzeptiert hast, stoppt Claude nicht mehr. Zieh es zurück, um wieder streng zu sein.",
    noExceptions: "Keine Ausnahmen.",
    retract: "Zurückziehen",
    avoided: "Letzte 30 Tage",
    nothingYet: "Sens hat in diesem Projekt noch nichts gestoppt.",
    copies: (count: number) => (count === 1 ? "1 Kopie gestoppt" : `${count} Kopien gestoppt`),
    dependencies: (count: number) => (count === 1 ? "1 Abhängigkeit abgelehnt" : `${count} Abhängigkeiten abgelehnt`),
    comments: (count: number) => (count === 1 ? "1 Kommentar gestoppt" : `${count} Kommentare gestoppt`),
    protectedFiles: (count: number) => (count === 1 ? "1 geschützte Datei bewahrt" : `${count} geschützte Dateien bewahrt`),
    tests: (count: number) => (count === 1 ? "1 Entfernen von Tests gestoppt" : `${count}-mal Entfernen von Tests gestoppt`),
    orphans: (count: number) => (count === 1 ? "1 ungenutzter Code gestoppt" : `${count}-mal ungenutzter Code gestoppt`),
    judgment: (count: number) => (count === 1 ? "1 Befund der Prüfung" : `${count} Befunde der Prüfung`),
    held: (count: number) => (count === 1 ? "1-mal zurückgehalten" : `${count}-mal zurückgehalten`),
    reviews: (count: number, cost: string) => (count === 1 ? `1 Prüfung · ${cost}` : `${count} Prüfungen · ${cost}`),
  },
  ja: {
    noProject: "プロジェクトを開くと、Sens がどう守っているかを確認できます。",
    rules: "プロジェクトのルール",
    noComments: "コードにコメントを書かない",
    noCommentsNote: "このプロジェクトで Claude が書くコメントを Sens が止めます。",
    exceptions: "例外",
    exceptionsNote: "承認したものはもう Claude を止めません。取り消すと再び厳格になります。",
    noExceptions: "例外はありません。",
    retract: "取り消す",
    avoided: "過去 30 日",
    nothingYet: "Sens はこのプロジェクトでまだ何も止めていません。",
    copies: (count: number) => `コピーを ${count} 件停止`,
    dependencies: (count: number) => `依存関係を ${count} 件拒否`,
    comments: (count: number) => `コメントを ${count} 件停止`,
    protectedFiles: (count: number) => `保護されたファイルを ${count} 件保持`,
    tests: (count: number) => `テストの削除を ${count} 件停止`,
    orphans: (count: number) => `使われないコードを ${count} 件停止`,
    judgment: (count: number) => `レビューの指摘 ${count} 件`,
    held: (count: number) => `${count} 回保留`,
    reviews: (count: number, cost: string) => `レビュー ${count} 回 · ${cost}`,
  },
  zh: {
    noProject: "打开一个项目，查看 Sens 如何守护它。",
    rules: "项目规则",
    noComments: "代码中不写注释",
    noCommentsNote: "Sens 会阻止 Claude 在此项目中写下的任何注释。",
    exceptions: "例外",
    exceptionsNote: "你接受过的内容不再阻止 Claude。撤回后将重新严格执行。",
    noExceptions: "没有例外。",
    retract: "撤回",
    avoided: "最近 30 天",
    nothingYet: "Sens 尚未在此项目中阻止任何内容。",
    copies: (count: number) => `阻止了 ${count} 处复制`,
    dependencies: (count: number) => `拒绝了 ${count} 个依赖`,
    comments: (count: number) => `阻止了 ${count} 条注释`,
    protectedFiles: (count: number) => `保住了 ${count} 个受保护文件`,
    tests: (count: number) => `阻止了 ${count} 次删除测试`,
    orphans: (count: number) => `阻止了 ${count} 处未使用代码`,
    judgment: (count: number) => `审查发现 ${count} 条`,
    held: (count: number) => `暂扣 ${count} 次`,
    reviews: (count: number, cost: string) => `审查 ${count} 次 · ${cost}`,
  },
});
