import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    noFolder: "No folder.",
    indexing: "Sens is indexing the project…",
    empty: "Sens found no code to map in this folder.",
    tally: (areas: number, files: number) => `${areas === 1 ? "1 area" : `${areas} areas`} · ${files === 1 ? "1 file" : `${files} files`}`,
    central: "Central files",
    centralSaid: "The files most others depend on",
    areas: "Areas",
    strays: "Out of place",
    straysSaid: "They work with another area more than with their own",
    files: (count: number) => (count === 1 ? "1 file" : `${count} files`),
    doors: "Entered through",
    uses: "Uses",
    exports: "Most used",
    dependents: (count: number) => (count === 1 ? "1 depends on it" : `${count} depend on it`),
    back: "Back to the map",
    reachOf: "What depends on this file",
    steps: (count: number) => (count === 1 ? "1 step" : `${count} steps`),
    nothingDepends: "Nothing in the project depends on it.",
    tests: "Tests that reach it",
    noTests: "No test reaches it.",
    inspect: "What depends on it",
    openInFiles: "Open in Files",
  },
  es: {
    noFolder: "Sin carpeta.",
    indexing: "Sens está indexando el proyecto…",
    empty: "Sens no encontró código que trazar en esta carpeta.",
    tally: (areas: number, files: number) => `${areas === 1 ? "1 área" : `${areas} áreas`} · ${files === 1 ? "1 fichero" : `${files} ficheros`}`,
    central: "Ficheros centrales",
    centralSaid: "Los ficheros de los que más dependen los demás",
    areas: "Áreas",
    strays: "Fuera de sitio",
    straysSaid: "Trabajan más con otra área que con la suya",
    files: (count: number) => (count === 1 ? "1 fichero" : `${count} ficheros`),
    doors: "Se entra por",
    uses: "Usa",
    exports: "Lo más usado",
    dependents: (count: number) => (count === 1 ? "1 depende de él" : `${count} dependen de él`),
    back: "Volver al mapa",
    reachOf: "Lo que depende de este fichero",
    steps: (count: number) => (count === 1 ? "1 paso" : `${count} pasos`),
    nothingDepends: "Nada del proyecto depende de él.",
    tests: "Tests que lo alcanzan",
    noTests: "Ningún test lo alcanza.",
    inspect: "Lo que depende de él",
    openInFiles: "Abrir en Ficheros",
  },
  fr: {
    noFolder: "Aucun dossier.",
    indexing: "Sens indexe le projet…",
    empty: "Sens n’a trouvé aucun code à cartographier dans ce dossier.",
    tally: (areas: number, files: number) => `${areas <= 1 ? `${areas} zone` : `${areas} zones`} · ${files <= 1 ? `${files} fichier` : `${files} fichiers`}`,
    central: "Fichiers centraux",
    centralSaid: "Les fichiers dont dépendent le plus les autres",
    areas: "Zones",
    strays: "Hors de leur place",
    straysSaid: "Ils travaillent plus avec une autre zone qu’avec la leur",
    files: (count: number) => (count <= 1 ? `${count} fichier` : `${count} fichiers`),
    doors: "On y entre par",
    uses: "Utilise",
    exports: "Le plus utilisé",
    dependents: (count: number) => (count <= 1 ? `${count} en dépend` : `${count} en dépendent`),
    back: "Retour à la carte",
    reachOf: "Ce qui dépend de ce fichier",
    steps: (count: number) => (count <= 1 ? `${count} étape` : `${count} étapes`),
    nothingDepends: "Rien dans le projet n’en dépend.",
    tests: "Tests qui l’atteignent",
    noTests: "Aucun test ne l’atteint.",
    inspect: "Ce qui en dépend",
    openInFiles: "Ouvrir dans Fichiers",
  },
  de: {
    noFolder: "Kein Ordner.",
    indexing: "Sens indiziert das Projekt …",
    empty: "Sens hat in diesem Ordner keinen Code zum Kartieren gefunden.",
    tally: (areas: number, files: number) => `${areas === 1 ? "1 Bereich" : `${areas} Bereiche`} · ${files === 1 ? "1 Datei" : `${files} Dateien`}`,
    central: "Zentrale Dateien",
    centralSaid: "Die Dateien, von denen die meisten anderen abhängen",
    areas: "Bereiche",
    strays: "Fehl am Platz",
    straysSaid: "Sie arbeiten mehr mit einem anderen Bereich als mit ihrem eigenen",
    files: (count: number) => (count === 1 ? "1 Datei" : `${count} Dateien`),
    doors: "Zugang über",
    uses: "Nutzt",
    exports: "Am meisten genutzt",
    dependents: (count: number) => (count === 1 ? "1 hängt davon ab" : `${count} hängen davon ab`),
    back: "Zurück zur Karte",
    reachOf: "Was von dieser Datei abhängt",
    steps: (count: number) => (count === 1 ? "1 Schritt" : `${count} Schritte`),
    nothingDepends: "Nichts im Projekt hängt davon ab.",
    tests: "Tests, die sie erreichen",
    noTests: "Kein Test erreicht sie.",
    inspect: "Was davon abhängt",
    openInFiles: "In Dateien öffnen",
  },
  ja: {
    noFolder: "フォルダーがありません。",
    indexing: "Sens がプロジェクトをインデックスしています…",
    empty: "このフォルダーにはマップにするコードが見つかりませんでした。",
    tally: (areas: number, files: number) => `${areas} 領域 · ${files} ファイル`,
    central: "中心のファイル",
    centralSaid: "ほかのファイルが最も依存しているファイル",
    areas: "領域",
    strays: "場所違い",
    straysSaid: "自分の領域より別の領域と多く連携しているファイル",
    files: (count: number) => `${count} ファイル`,
    doors: "入口",
    uses: "使用先",
    exports: "よく使われるもの",
    dependents: (count: number) => `${count} 件が依存`,
    back: "マップに戻る",
    reachOf: "このファイルに依存しているもの",
    steps: (count: number) => `${count} ステップ`,
    nothingDepends: "プロジェクト内でこれに依存するものはありません。",
    tests: "これに届くテスト",
    noTests: "これに届くテストはありません。",
    inspect: "依存しているもの",
    openInFiles: "ファイルで開く",
  },
  zh: {
    noFolder: "没有文件夹。",
    indexing: "Sens 正在索引项目…",
    empty: "Sens 在此文件夹中没有找到可绘制的代码。",
    tally: (areas: number, files: number) => `${areas} 个区域 · ${files} 个文件`,
    central: "核心文件",
    centralSaid: "其他文件最依赖的文件",
    areas: "区域",
    strays: "位置不当",
    straysSaid: "与其他区域的联系多于与本区域的联系",
    files: (count: number) => `${count} 个文件`,
    doors: "入口",
    uses: "使用",
    exports: "最常用",
    dependents: (count: number) => `${count} 个依赖它`,
    back: "返回地图",
    reachOf: "依赖此文件的内容",
    steps: (count: number) => `${count} 步`,
    nothingDepends: "项目中没有任何内容依赖它。",
    tests: "能覆盖到它的测试",
    noTests: "没有测试覆盖到它。",
    inspect: "依赖它的内容",
    openInFiles: "在文件中打开",
  },
});
