import { shared } from "../shared/copy";
import { copy } from "../shared/i18n";

export const t = copy({
  en: {
    placeholder: "Ask Sens for what you need",
    message: "Message for Sens",
    where: (name: string, session: string) => `${name} · ${session}. ${shared.ctrl}+Tab switches the project`,
    newSession: "New session",
    newSessionThere: "new session",
    sessions: "Sessions",
    otherProjects: "Other projects",
    search: "Find a session or a project",
    choices: "Where to ask",
    nothingFound: "No session or project by that name",
    projects: "Projects",
    noProject: "Open a project in Sens first",
    send: "Send",
    stop: "Stop",
    stopping: "Stopping…",
    shot: (app: string) => `${app} · capture`,
    shotAdd: (app: string) => `Add a capture of ${app}`,
    clip: "Clipboard",
    clipAdd: "Add what you copied",
    remove: (name: string) => `Remove ${name}`,
    pastedText: (lines: number) => (lines === 1 ? "Pasted text · 1 line" : `Pasted text · ${lines} lines`),
    openInSens: "open in Sens",
    pin: "pin",
    unpin: "unpin",
    close: "close",
    pinned: "Pinned: it stays on top until you unpin it",
    pinAction: "Pin: it stays visible over every window on this screen (Ctrl+P)",
    move: "Drag to move it · double-click to center it",
    reads: (count: number) => (count === 1 ? "1 file read" : `${count} files read`),
  },
  es: {
    placeholder: "Pide lo que necesites a Sens",
    message: "Mensaje para Sens",
    where: (name: string, session: string) => `${name} · ${session}. ${shared.ctrl}+Tab cambia de proyecto`,
    newSession: "Nueva sesión",
    newSessionThere: "nueva sesión",
    sessions: "Sesiones",
    otherProjects: "Otros proyectos",
    search: "Busca una sesión o un proyecto",
    choices: "Dónde preguntar",
    nothingFound: "Ninguna sesión ni proyecto se llama así",
    projects: "Proyectos",
    noProject: "Abre antes un proyecto en Sens",
    send: "Enviar",
    stop: "Parar",
    stopping: "Parando…",
    shot: (app: string) => `${app} · captura`,
    shotAdd: (app: string) => `Añadir una captura de ${app}`,
    clip: "Portapapeles",
    clipAdd: "Añadir lo que copiaste",
    remove: (name: string) => `Quitar ${name}`,
    pastedText: (lines: number) => (lines === 1 ? "Texto pegado · 1 línea" : `Texto pegado · ${lines} líneas`),
    openInSens: "abrir en Sens",
    pin: "fijar",
    unpin: "soltar",
    close: "cerrar",
    pinned: "Fijada: se queda encima hasta que la sueltes",
    pinAction: "Fijar: se queda visible sobre cualquier ventana de esta pantalla (Ctrl+P)",
    move: "Arrastra para moverla · doble clic para centrarla",
    reads: (count: number) => (count === 1 ? "1 fichero leído" : `${count} ficheros leídos`),
  },
  fr: {
    placeholder: "Demandez à Sens ce dont vous avez besoin",
    message: "Message pour Sens",
    where: (name: string, session: string) => `${name} · ${session}. ${shared.ctrl}+Tab change de projet`,
    newSession: "Nouvelle session",
    newSessionThere: "nouvelle session",
    sessions: "Sessions",
    otherProjects: "Autres projets",
    search: "Chercher une session ou un projet",
    choices: "Où demander",
    nothingFound: "Aucune session ni aucun projet de ce nom",
    projects: "Projets",
    noProject: "Ouvrez d’abord un projet dans Sens",
    send: "Envoyer",
    stop: "Arrêter",
    stopping: "Arrêt…",
    shot: (app: string) => `${app} · capture`,
    shotAdd: (app: string) => `Ajouter une capture de ${app}`,
    clip: "Presse-papiers",
    clipAdd: "Ajouter ce que vous avez copié",
    remove: (name: string) => `Retirer ${name}`,
    pastedText: (lines: number) => (lines <= 1 ? `Texte collé · ${lines} ligne` : `Texte collé · ${lines} lignes`),
    openInSens: "ouvrir dans Sens",
    pin: "épingler",
    unpin: "détacher",
    close: "fermer",
    pinned: "Épinglée : elle reste au premier plan jusqu’à ce que vous la détachiez",
    pinAction: "Épingler : elle reste visible par-dessus toutes les fenêtres de cet écran (Ctrl+P)",
    move: "Faites-la glisser pour la déplacer · double-clic pour la centrer",
    reads: (count: number) => (count <= 1 ? `${count} fichier lu` : `${count} fichiers lus`),
  },
  de: {
    placeholder: "Frag Sens, was du brauchst",
    message: "Nachricht an Sens",
    where: (name: string, session: string) => `${name} · ${session}. ${shared.ctrl}+Tab wechselt das Projekt`,
    newSession: "Neue Sitzung",
    newSessionThere: "neue Sitzung",
    sessions: "Sitzungen",
    otherProjects: "Andere Projekte",
    search: "Sitzung oder Projekt suchen",
    choices: "Wo fragen",
    nothingFound: "Keine Sitzung und kein Projekt mit diesem Namen",
    projects: "Projekte",
    noProject: "Öffne zuerst ein Projekt in Sens",
    send: "Senden",
    stop: "Stoppen",
    stopping: "Wird gestoppt…",
    shot: (app: string) => `${app} · Aufnahme`,
    shotAdd: (app: string) => `Eine Aufnahme von ${app} hinzufügen`,
    clip: "Zwischenablage",
    clipAdd: "Hinzufügen, was du kopiert hast",
    remove: (name: string) => `${name} entfernen`,
    pastedText: (lines: number) => (lines === 1 ? "Eingefügter Text · 1 Zeile" : `Eingefügter Text · ${lines} Zeilen`),
    openInSens: "in Sens öffnen",
    pin: "anheften",
    unpin: "lösen",
    close: "schließen",
    pinned: "Angeheftet: Sie bleibt im Vordergrund, bis du sie löst",
    pinAction: "Anheften: Sie bleibt auf diesem Bildschirm über jedem Fenster sichtbar (Strg+P)",
    move: "Zum Verschieben ziehen · Doppelklick zentriert sie",
    reads: (count: number) => (count === 1 ? "1 Datei gelesen" : `${count} Dateien gelesen`),
  },
  ja: {
    placeholder: "Sens に頼みたいことを入力",
    message: "Sens へのメッセージ",
    where: (name: string, session: string) => `${name} · ${session}。${shared.ctrl}+Tab でプロジェクトを切り替え`,
    newSession: "新しいセッション",
    newSessionThere: "新しいセッション",
    sessions: "セッション",
    otherProjects: "ほかのプロジェクト",
    search: "セッションまたはプロジェクトを検索",
    choices: "質問する場所",
    nothingFound: "その名前のセッションやプロジェクトはありません",
    projects: "プロジェクト",
    noProject: "先に Sens でプロジェクトを開いてください",
    send: "送信",
    stop: "停止",
    stopping: "停止中…",
    shot: (app: string) => `${app} · キャプチャ`,
    shotAdd: (app: string) => `${app} のキャプチャを追加`,
    clip: "クリップボード",
    clipAdd: "コピーした内容を追加",
    remove: (name: string) => `${name} を削除`,
    pastedText: (lines: number) => `貼り付けたテキスト · ${lines} 行`,
    openInSens: "Sens で開く",
    pin: "固定",
    unpin: "固定を解除",
    close: "閉じる",
    pinned: "固定中: 解除するまで最前面に表示されます",
    pinAction: "固定: この画面のどのウィンドウよりも前面に表示し続けます (Ctrl+P)",
    move: "ドラッグで移動 · ダブルクリックで中央へ",
    reads: (count: number) => `${count} 個のファイルを読み込み`,
  },
  zh: {
    placeholder: "告诉 Sens 你需要什么",
    message: "发给 Sens 的消息",
    where: (name: string, session: string) => `${name} · ${session}。按 ${shared.ctrl}+Tab 切换项目`,
    newSession: "新会话",
    newSessionThere: "新会话",
    sessions: "会话",
    otherProjects: "其他项目",
    search: "查找会话或项目",
    choices: "在哪里提问",
    nothingFound: "没有这个名字的会话或项目",
    projects: "项目",
    noProject: "请先在 Sens 中打开一个项目",
    send: "发送",
    stop: "停止",
    stopping: "正在停止…",
    shot: (app: string) => `${app} · 截图`,
    shotAdd: (app: string) => `添加 ${app} 的截图`,
    clip: "剪贴板",
    clipAdd: "添加你复制的内容",
    remove: (name: string) => `移除 ${name}`,
    pastedText: (lines: number) => `粘贴的文本 · ${lines} 行`,
    openInSens: "在 Sens 中打开",
    pin: "固定",
    unpin: "取消固定",
    close: "关闭",
    pinned: "已固定：取消固定前会一直置顶",
    pinAction: "固定：在此屏幕上始终显示在所有窗口之上 (Ctrl+P)",
    move: "拖动以移动 · 双击居中",
    reads: (count: number) => `已读取 ${count} 个文件`,
  },
});
