import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    profile: "Profile",
    settings: "Settings",
    shortcuts: "Keyboard shortcuts",
    about: "About Sens",
    noName: "No name",
    send: "Send",
    newLine: "New line",
    paste: "Paste a picture into the message",
    sidebar: "Show or hide the sidebar",
    openFolder: "Open folder",
    terminal: "Show or hide the terminal",
    arrange: "Open the arrangement",
    calm: "Only the conversation, or back",
    kept: "A kept arrangement",
  },
  es: {
    profile: "Perfil",
    settings: "Ajustes",
    shortcuts: "Atajos de teclado",
    about: "Acerca de Sens",
    noName: "Sin nombre",
    send: "Enviar",
    newLine: "Nueva línea",
    paste: "Pegar una imagen en el mensaje",
    sidebar: "Mostrar u ocultar la barra lateral",
    openFolder: "Abrir carpeta",
    terminal: "Mostrar u ocultar la terminal",
    arrange: "Abrir la disposición",
    calm: "Solo la conversación, o volver",
    kept: "Una disposición guardada",
  },
  fr: {
    profile: "Profil",
    settings: "Paramètres",
    shortcuts: "Raccourcis clavier",
    about: "À propos de Sens",
    noName: "Sans nom",
    send: "Envoyer",
    newLine: "Nouvelle ligne",
    paste: "Coller une image dans le message",
    sidebar: "Afficher ou masquer la barre latérale",
    openFolder: "Ouvrir un dossier",
    terminal: "Afficher ou masquer le terminal",
    arrange: "Ouvrir la disposition",
    calm: "Seulement la conversation, ou revenir",
    kept: "Une disposition enregistrée",
  },
  de: {
    profile: "Profil",
    settings: "Einstellungen",
    shortcuts: "Tastenkürzel",
    about: "Über Sens",
    noName: "Kein Name",
    send: "Senden",
    newLine: "Neue Zeile",
    paste: "Bild in die Nachricht einfügen",
    sidebar: "Seitenleiste ein- oder ausblenden",
    openFolder: "Ordner öffnen",
    terminal: "Terminal ein- oder ausblenden",
    arrange: "Anordnung öffnen",
    calm: "Nur das Gespräch, oder zurück",
    kept: "Eine gespeicherte Anordnung",
  },
  ja: {
    profile: "プロフィール",
    settings: "設定",
    shortcuts: "キーボードショートカット",
    about: "Sens について",
    noName: "名前なし",
    send: "送信",
    newLine: "改行",
    paste: "メッセージに画像を貼り付け",
    sidebar: "サイドバーの表示・非表示",
    openFolder: "フォルダーを開く",
    terminal: "ターミナルの表示・非表示",
    arrange: "レイアウトを開く",
    calm: "会話のみ、または元に戻す",
    kept: "保存したレイアウト",
  },
  zh: {
    profile: "个人资料",
    settings: "设置",
    shortcuts: "键盘快捷键",
    about: "关于 Sens",
    noName: "未命名",
    send: "发送",
    newLine: "换行",
    paste: "在消息中粘贴图片",
    sidebar: "显示或隐藏侧边栏",
    openFolder: "打开文件夹",
    terminal: "显示或隐藏终端",
    arrange: "打开布局",
    calm: "仅对话，或恢复",
    kept: "已保存的布局",
  },
});
